### ISSUE TITLE
Can claim in worldguard protected areas

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#633] opened 2019-09-30 22:58 UTC
### What happened:
People can claim in worldguarded regions

### What you expected:
People shouldnt be allowed to do that
### Steps to reproduce:
try and claim in a worldguarded area

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-paper-597 MC: 1.13.2
Paste of `/version GriefPrevention`: 16.11.4

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

https://pastebin.com/rg6ut6eK

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):

**Comment by RoboMWM** [comment] 2019-10-01 03:30
Probably a duplicate of #627 

Closing due to insufficient information provided (primarily no reproduction steps amongst other things).

**Closed as completed by RoboMWM** 2019-10-01 03:30 UTC
Labels: 🚫Invalid

**Comment by JHarris12345** [comment] 2019-10-01 13:24
Yes but @RoboMWM when I have the setting "CreationRequiresWorldGuardbuildPermission: true" the console says this:

[Tue, 1. Oct 2019 06:23:07 MST INFO] WorldGuard is out of date. Please update or remove WorldGuard, or disable WorldGuard integration in GP's config (CreationRequiresWorldGuardBuildPermission)

Even though it is up to date? And people can still make claims

**Comment by Jikoo** [comment] 2019-10-01 14:23
The changelogs for the 2 GP versions you are behind both contain updates for WG changing their API without bumping API version.

**Comment by RoboMWM** [comment] 2019-10-01 19:34
Ok, not a duplicate then. Just an out-of-date version of GP. Thanks for pointing that out Jikoo.
