### ISSUE TITLE
Fire Arrows Blowing up Claimed TNT

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1683] opened 2021-11-28 23:17 UTC
### Observed Behavior

When shooting TNT with a fire arrow from outside or inside of a claim, **trusted or untrusted**, it explodes the TNT. It does not cause block or player damage.

**TNT can be destroyed by anyone with a bow with the claim enchant an an arrow running the GriefPrevention plugin.**

### Expected Behavior

None of the TNT should explode, if the player is not trusted.

### Reproduction steps

Place TNT in claim, fire from inside or outside of claim when **untrusted** and watch the TNT explode.

### Stack trace or error log

```shell
No error displayed.
```

### Server version

```shell
This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
https://paste.lucko.me/rXSZOmcPEn
```

### Plugin list

```shell
https://paste.lucko.me/EDeLxQHmyh
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-11-29 01:38
Duplicate of #1401

**Closed as completed by Jikoo** 2021-11-29 01:38 UTC
