### ISSUE TITLE
Items can be removed from Glow Item Frames

### ISSUE THREAD

**Issue by TheLeby9** [GriefPrevention/GriefPrevention#1509] opened 2021-08-06 13:18 UTC
### What happened:
Placing an item in a glow item frame in a claim allow other untrusted players to remove that item from the frame .

### What was expected:
I expect it to be protected and prevent people from interacting with it and remove the items.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Place glow item frame in claimed area
2. Place item inside item frame
3. get and untrusted person to interact and click the glow item frame
4. they will be able to remove the item from the glow item frame even if its claimed and they are untrusted

### Server and GriefPrevention version:

Paste of `/version`: This server is running Purpur version git-Purpur-1262 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 162d05f on HEAD)
You are 52 version(s) behind
Previous version: git-Purpur-1199 (MC: 1.17)
Paste of `/version GriefPrevention`: 16.17.1-2b69191

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment] 2021-08-06 13:29
Dupe of issues #1435 and #1487 and #1507. 

#1435 has steps to download a dev build that will fix this e.g. https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/39942636/artifacts until a proper release is made.

There should be a full release in the not too distant future with 1.17 fixes like this, but in the meantime, you could just take a recent CI build from https://ci.appveyor.com/project/RoboMWM39862/griefprevention - usual "CI build not yet fully tested and approved for release, there may be dragons" disclaimer applies.

**Closed as completed by bigpresh** 2021-08-06 13:29 UTC
