### ISSUE TITLE
1.16 wooden fences (crimson and warped) do not lock in claims

### ISSUE THREAD

**Issue by cunhar** [GriefPrevention/GriefPrevention#920] opened 2020-07-30 19:19 UTC
### What happened:
1.16 wooden fences (crimson and warped) do not lock in claims

### What was expected:
fences staying closed by people whom dont have access

### Steps to reproduce:
1. Player 1 Claims 1.16 fences
2. Player 2 Opens Fence
3. ???
4. Player 1 sad :(

### Server and GriefPrevention version:
16.14.0

### GriefPrevention config.yml

```yml
    LockFenceGates: true
```

**Comment by Jikoo** [comment] 2020-07-30 19:39
Duplicate of #886

**Closed as completed by Jikoo** 2020-07-30 19:39 UTC
