### ISSUE TITLE
1.17.1 glowing itemframe bug

### ISSUE THREAD

**Issue by Tizooo** [GriefPrevention/GriefPrevention#1493] opened 2021-07-27 18:04 UTC
Hey my server is running Purpur version git-Purpur-1296 (MC: 1.17.1) if u have a glowing itemframe with a item in it other players can still take out the item even if it is claimed.

**Comment by Jikoo** [comment] 2021-07-27 23:32
Duplicate of #1435

**Closed as completed by Jikoo** 2021-07-27 23:32 UTC
