### ISSUE TITLE
[bug] untrust inactive player fails

### ISSUE THREAD

**Issue by ScuroK** [GriefPrevention/GriefPrevention#287] opened 2018-05-10 19:19 UTC
GP-VERSION: 16.8
SPIGOT: 1.12.2 (latest)

A player was not online since 96 days. Now i cant /untrust him from an area. 
I get the message  that no player with this name has recently loged in. but he is listen in /trustlist.

can you fix this please?

**Comment by RoboMWM** [comment] 2018-05-10 21:49
Not a bug, and duplicate of #238

**Closed as completed by RoboMWM** 2018-05-10 21:49 UTC
