### ISSUE TITLE
Grief Prevention -> Luck Perms / Ranks

### ISSUE THREAD

**Issue by Reiamsei** [GriefPrevention/GriefPrevention#1206] opened 2021-01-15 09:18 UTC
My Problem:
I want to give diffrent ranks a diffrent amount of InitialBlocks and a diffrent amount of Claims.
Default : 
InitialBlocks: 1000
MaximumNumberOfClaimsPerPlayer: 1
Premium : 
InitialBlocks: 2000
MaximumNumberOfClaimsPerPlayer: 2
....

so that, when I give Player the rank Premium, he gets 2000 Blocks to claim, and when he gets Default back he only has 1000 Blocks again.
The same with the max numver of claims.

I tried to use /acb , but this is not working and dont make any sence when you have more then 2 ranks in my opinion...

### Server and GriefPrevention version:
Server Version : 1.16.4
Grief Prevention version : 16.16.0
Luckperms version : 5.2.76

would be awesome, if someone can help me !
sorry for my bad english

**Comment by RoboMWM** [comment] 2021-01-15 17:58
this is not a bug, this is an addon suggestion. Moving to discussions.

**Closed as completed** 2021-01-15 17:58 UTC
