### ISSUE TITLE
Crimson door & Warped door are not protected

### ISSUE THREAD

**Issue by morelaid** [GriefPrevention/GriefPrevention#954] opened 2020-08-09 09:59 UTC
### What happened:
If the new Nether doors are used, then unfortunately they are not protected. This means that players can simply walk through these doors even though they have no rights (are not trusted).

### What was expected:
I would expect that players can only go through these doors if they have the appropriate rights. Just like the normal doors.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Place a nether door
2. Do not set a permission for another player
3. The other player can open the door

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Previous version: git-Paper-129 (MC: 1.16.1) | This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

### Stack trace/error or server log
No error in console....

Or, paste the server.log at gist.github.com and paste the link here: 
No errors, so so server.log needed.

**Comment by Jikoo** [comment] 2020-08-09 13:39
Duplicate of #886

**Closed as completed by Jikoo** 2020-08-09 13:39 UTC
