### ISSUE TITLE
Berry bug 1.14.x

### ISSUE THREAD

**Issue by successed** [GriefPrevention/GriefPrevention#550] opened 2019-06-17 22:05 UTC
other player, use my berry farm.

server version 1.14.2

**Comment by Jikoo** [comment] 2019-06-17 22:10
Duplicate of #548

**Comment by RoboMWM** [comment] 2019-06-18 17:25
Thanks jikoo.

Duplicate of #548

**Comment by RoboMWM** [comment] 2019-06-18 17:25
Duplicate of #548

**Closed as completed by RoboMWM** 2019-06-18 17:25 UTC
