### ISSUE TITLE
Remove negative claimblock "autofix"

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#235] opened 2017-12-09 02:57 UTC
Note: I'm looking for a developer who can add an option in GPRealEstate which transfers claimblocks upon the purchase of a land claim. This would prevent GPRealEstate from creating a negative claimblock balance. However, I thought you might also want to look at the issue.

I am willing to pay for this fix to GPRealEstate, so if anyone is interested to add a feature and earn some money please let me know.

It seems like GriefPrevention is trying to recalculate the claimblocks.

### What behaviour is expected:
Players unable to create a negative claimblock balance. Or, if negative claimblock balance is achieved then claim blocks will not be duplicated as a result.
### What behaviour is observed:
having a negative claimblock balance duplicated claimblocks on server reset. All "Bonus blocks" get duplicated and put into "Claimblocks from play" balance, resulting in something like twice as many Bonus blocks.
### Steps/models to reproduce:
Depends on the ability to produce a negative claimblock balance. This can be acheived using GPRealEstate.
1) Create a land claim which is larger than the available claim blocks of a second player.
2) Offer to sell that land claim to the second player using GPRealEstate
3) Second player purchases. Claimblocks from the claim go to the seller. Buyer now has a negative balance.
4) Restart the server.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Latest version of spigot and GriefPrevention. Latest version of GPRealEstate.

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Survival
      world: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 2
    MinimumArea: 8
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_AXE
    Expiration:
      ChestClaimDays: 28
      UnusedClaimDays: 28
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 50000
        ExceptWhenOwnerHasBonusClaimBlocks: 100000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 10
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 20.0
    ClaimBlocksSellValue: 20.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 227:*:Battery Box
    - 130:*:Transmutation Tablet
    - 128:*:Alchemical Chest and Energy Condenser
    - 181:*:Various Chests
    - 178:*:Ender Chest
    - 150:*:Various BuildCraft Gadgets
    - 155:*:Filler
    - 157:*:Builder
    - 158:*:Template Drawing Table
    - 126:*:Various EE Gadgets
    - 138:*:Various RedPower Gadgets
    - 137:*:BuildCraft Project Table and Furnaces
    - 250:*:Various IC2 Machines
    - 161:*:BuildCraft Engines
    - 169:*:Automatic Crafting Table
    - 177:*:Wireless Components
    - 183:*:Solar Arrays
    - 187:*:Charging Benches
    - 188:*:More IC2 Machines
    - 190:*:Generators, Fabricators, Strainers
    - 194:*:More Gadgets
    - 207:*:Computer
    - 208:*:Computer Peripherals
    - 246:*:IC2 Generators
    - 24303:*:Teleport Pipe
    - 24304:*:Waterproof Teleport Pipe
    - 24305:*:Power Teleport Pipe
    - 4311:*:Diamond Sorting Pipe
    - 216:*:Turtle
    BlockIdsExplodable:
    - 161:*:BuildCraft Engines
    - 246:5:Nuclear Reactor
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 14
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


### Plugin list (if applicable):
All latest versions of 
Spigot
Essentials
GriefPrevention
GPRealEstate

**Comment by RoboMWM** [comment] 2017-12-09 14:01
Btw, "all latest versions" isn't a version, otherwise thanks for actually filling out the template.

Yes, GP does do this, presumably to correct issues. I'm not sure why it does, but I do know this is a duplicate issue I believe (don't have time right now to figure out which issue it's a duplicate of but I'm pretty sure someone else complained about this before and I responded to it... unless that was just spigot discussion).

**Comment by NullCase** [comment] 2017-12-10 09:15
How much is your time worth?

I'm grateful for your response of course, but my only interest is to have a solution. And I am happy to pay if i can to help that along.

I guess i can hire a therapist if i just want someone to respond to my complaining. Or perhaps a dog, but this is too cruel. I hope you're not a dog. On the internet no one knows if you're a dog.

SO, how about I learn what your time is worth, and maybe I can pay you something to fix a problem. Keep in mind of course, i just run a minecraft server and my access to money is what a minecraft server does.

Have a great weekend.

**Comment by RoboMWM** [comment] 2017-12-12 01:41
My time this week is worth a _lot,_ maybe next week I'll have time to look into disabling it and releasing a hotfix. Anyone else is also free to PR an option for this as well.

**Comment by NullCase** [comment] 2017-12-12 02:56
Thanks. I'll write here again in a week. Best of luck with your busy schedule.

**Comment by NullCase** [comment] 2017-12-18 14:15
Hi RoboMWM!

I'm ready to make a deal. 

My goal is to pay you an amount of money that's worth _more_ to you than the cost to solve this problem AND costs me _less_ than the value you provide by solving this problem. Simple enough, right? If we can find that price then we both win. So my goal is for both of us to win.

Will you accept paypal? When can you solve this problem by? How much does this solution cost?

When you turn off the feature which produces this bug, please include an option to leave it off. It seems to me that would be enough for me.

**Comment by RoboMWM** [comment] 2017-12-19 05:24
I still haven't really looked into how paypal handles stuff, but uh if you want I guess you could try the patreon I setup some time ago ¯\\\_(ツ)_/¯ https://www.patreon.com/RoboMWM

I'll try getting it done by this week or earlier. Will upload something here that you can test, and then will push live after you can verify it's working fine.

**Comment by RoboMWM** [comment] 2017-12-19 05:47
Change the following file extension from `.zip` to `.jar`
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/1570487/GriefPrevention.zip)

The config option should be under Advanced.fixNegativeClaimblockAmounts. Defaults to true (default behavior). Set this to false, and let me know if this fixes the issue. Also include the output of `/version GriefPrevention`

**Comment by NullCase** [comment] 2017-12-19 19:43
OK, The current verison of GriefPrevention I have and run is GriefPrevention version 16.7.1

Also, in case you wanted the version name you provided, it's GriefPrevention version 16.8-RC1. 

Test methods:

0) I first replaced the version of GreifPrevention to use the version you provided. I also changed the default setting of Advanced.fixNegativeClaimblockAmounts to false.
1) Created land claims to use up my available claim blocks
2) Saved and stopped the server.
3) Edited my GriefPreventionData/PlayerData so that I had 0 claimblocks from play. The idea here is when I start the server again I expect to have a negative claim balance. I would not have enough claim blocks to cover the claims I own.

Results: When I started the server up, my total claimblocks were duplicated. I did this a few times and eventually hit the maximum (1 million claimblocks from play). Edit: additionally, when i stop the server that's when my GriefPreventionData/PlayerData file is saved. Before the server is stopped the file is unchanged. When the server is stopped my claimblock count is saved and it displays the duplicated claimblocks in the PlayerData file.

Conclusion: Claimblocks are still duplicated on server restart when a player has more land claimed than their available Claimblocks would allow. A negative claimblock balance is not observed. Claimblocks are duplicated.

Is there something else I should try?

Also, I looked at patreon. Can you add an option for a 1 time payment? I'm hoping to use paypal at patreon for a 1 time payment.

**Comment by RoboMWM** [comment] 2017-12-19 19:58
> Edited my GriefPreventionData/PlayerData so that I had 0 claimblocks from play. The idea here is when I start the server again I expect to have a negative claim balance. I would not have enough claim blocks to cover the claims I own.

Is it possible you can try to use the GPRealEstate plugin instead of manually editing this file? I'm not sure if that's what the plugin modifies. I'll check again where it attempts to modify the player's accrued blocks when enumerating their claims - I recall seeing it, but I guess my search was too narrow when I made the change yesterday.

Also just saw the referenced issue pop up as I type this - that would be the proper way to do this, since GP assumes the "conservation of accrued claim blocks."

**Comment by RoboMWM** [comment] 2017-12-19 20:00
> Also, I looked at patreon. Can you add an option for a 1 time payment? I'm hoping to use paypal at patreon for a 1 time payment.

Appears not to be possible at the moment :/ Though you can try what they suggest https://patreon.zendesk.com/hc/en-us/articles/204606215-Can-I-make-a-one-time-payment-

**Comment by RoboMWM** [comment] 2017-12-19 20:06
@NullCase It appears that GP should be spitting out a ton of debug messages if it's fixing negative claim block values. Can you please enable debug mode in the config and check GP's logs?

**Comment by RoboMWM** [comment] 2017-12-19 20:55
Let me know if it's doing stuff in debug messages with RC1, then you can test this one:
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/1573229/GriefPrevention.zip)

**Comment by NullCase** [comment] 2017-12-19 21:57
OK I enable debug mode but kept everything else constant so it's a good comparison, just for a first retest.

Here's the log file. This is with RC1 and fixNegative... set to false. Looks like it still fixes the negative claim blocks, but  you will know for sure so here's the log file.

[2017_12_19.log](https://github.com/TechFortress/GriefPrevention/files/1573378/2017_12_19.log)

**Comment by NullCase** [comment] 2017-12-19 22:00
Good news! The latest version seems to have worked. 

I am correctly displaying a negative claim block balance. 
Claim blocks were not duplicated!
No errors in the log file.

**Comment by RoboMWM** [comment] 2017-12-19 22:06
Thanks!

**Closed as completed by RoboMWM** 2017-12-19 22:06 UTC
Labels: Improvement

**Comment by NullCase** [comment] 2017-12-19 22:08
OK, I've just reconfirmed this test using GPRealEstate. Buying a land claim to producing a negative claim balance and restarting the server does NOT duplicate blocks.

From my perspective you've fixed the problem. Really great job!

So, let's talk money. How much does this fix cost?

**Comment by NullCase** [comment] 2017-12-20 13:26
@RoboMWM please read the message above.

Also, I am still looking for a developer to fill this [request.](https://github.com/SuperPyroManiac/GPRealEstate/issues/8) As before I'm interested to pay an amount which is win/win.

**Comment by RoboMWM** [comment] 2017-12-20 16:41
Don't really want to discuss money stuff on the issue tracker, but you can donate as much as you wish I guess. Fortunately didn't take too long (though I did have to resetup my dev environment due to where I am). [I'm on IRC](http://irc.spi.gt/iris/?nick=&channels=GriefPrevention) if you want to discuss further; I've also re-enabled PMs temporarily on spigot if you don't catch me online.

**Comment by NullCase** [comment] 2017-12-21 17:13
Right, as much as I wish less the amount I don't have, of course. And recall that I wish to pay you an amount which is less than the value you have provided me. If i fail to do this then i cannot benefit from this solution. And I wish to pay you an amount that's worth more to you that the cost to fix this. If you are not paid an amount like this then you don't win. Quite often there is an amount between those two and we can both benefit in the end.

I've created a conversation on Spigot.
