### ISSUE TITLE
glow item frame 

### ISSUE THREAD

**Issue by toonystank** [GriefPrevention/GriefPrevention#1507] opened 2021-08-05 13:15 UTC
### What happened:
people can take out the item from glow item frame inside a claim

### What was expected:
glow item frame must work same as normal item frame

### Server and GriefPrevention version:

[13:13:50 INFO]: This server is running Purpur version git-Purpur-1271 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5590265 on HEAD)

GriefPrevention latest public version

### Stack trace/error or server log

no error

**Comment by bigpresh** [comment] 2021-08-05 13:18
Dupe of #1435 and #1487.  #1435 has steps to download a dev build that will fix this e.g. https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/39942636/artifacts until a proper release is made.

EDIT: or just take most recent CI build from https://ci.appveyor.com/project/RoboMWM39862/griefprevention rather than the particular one I linked to.  Either way, usual "CI build not yet fully tested and approved for release, there may be dragons" disclaimer applies.

**Closed as completed by bigpresh** 2021-08-05 13:18 UTC
