### ISSUE TITLE
Plugin doesn't work with 1.12?

### ISSUE THREAD

**Issue by Chenchoon** [GriefPrevention/GriefPrevention#157] opened 2017-06-23 12:11 UTC
### What behaviour is expected: 
It's supposed to let you claim land
### What behaviour is observed: 
It doesn't claim land at all no matter what you try, the first corner is fine but when you try the other it doesn't work.
### Steps/models to reproduce:
Get a gold shovel go right click the 2 opposite corners of a claim that's 10x10 or more.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
spigot 16.6

This plugin worked great until I updated to 1.12

**Comment by bigpresh** [comment] 2017-06-23 12:20
What GriefPrevention version are you using (as requested in the issue template)?

Works fine for me, with 16.7.1 on 1.12.

**Comment by Chenchoon** [comment] 2017-06-23 15:55
I'm using version  16.6

**Comment by bigpresh** [comment] 2017-06-23 16:06
Try 16.7.1 and report back, please?

**Comment by RoboMWM** [comment] 2017-06-23 21:35
Also make sure you update (or remove) worldguard, if you're using it.

**Comment by Chenchoon** [comment] 2017-06-24 14:50
Ok it still wont work :(

**Comment by Chenchoon** [comment] 2017-06-24 14:54
It works

**Comment by Chenchoon** [comment] 2017-06-24 14:54
world guard was the problem

**Comment by RoboMWM** [comment] 2017-06-24 18:06
Duplicate of #147

**Closed as completed by RoboMWM** 2017-06-24 18:06 UTC

**Comment by bigpresh** [comment] 2017-06-24 19:32
> world guard was the problem

Thanks for taking the time to respond to confirm you got to the bottom of it :)
