### ISSUE TITLE
Players can claim land in WorldGuard region

### ISSUE THREAD

**Issue by ShawnPR1** [GriefPrevention/GriefPrevention#493] opened 2019-03-12 16:19 UTC
### What happened:
Players can claim land in a WorldGuard protected region

### What you expected:
Seeing as players do not have access to build in said region, I took it they won't be able to claim land there

### Steps to reproduce:
1. Create region (expand vert to ensure all blocks are covered)
2. Ensure players can't build there (which they can't)
3. Player claims land inside the region using golden shovel

### Server and GriefPrevention version:
Paste of `/version`: 1.13.2-R0.1-SNAPSHOT
Paste of `/version GriefPrevention`: 16.11.5

### Stack trace/error or server log
Not applicable

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    VikingsDen: -1
    VikingsDen_nether: -1
    VikingsDen_the_end: -1
    Creative: -1
    Hub: -1
    Road: -1
    Flat: -1
  Claims:
    Mode:
      Road: Survival
      VikingsDen_the_end: Survival
      Hub: Survival
      VikingsDen: Survival
      Creative: Disabled
      VikingsDen_nether: Survival
      Flat: Survival
    PreventGlobalMonsterEggs: false
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 20
    MinimumWidth: 2
    MinimumArea: 4
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 180
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: true
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      VikingsDen: true
      VikingsDen_nether: true
      VikingsDen_the_end: true
      Creative: true
      Hub: true
      Road: true
      Flat: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 20.0
    ClaimBlocksSellValue: 20.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

Take note that above I have CreationRequiresWorldGuardBuildPermission set to true. I have restarted the server as well to ensure the config file is loaded properly.

I'm quite new to using GriefPrevention and I hope it's not simply some stupid thing I've missed. Players don't have permissions to bypass this at all (I don't even think there's a permission node for that).

I also want to state that players cannot build in the region I have claimed and I have even tested it by creating new claims and they can still claim land there but not build/break blocks inside said claim.

What could I possibly be missing? This plugin is amazing, but it's quite annoying to have to re-claim the region using GriefPrevention then trusting everyone just so they can't claim land there.

**Comment by bigpresh** [comment] 2019-03-12 16:34
First thing to check, in your server log when GriefPrevention is loading as it starts, do you see a message of `Successfully hooked into WorldGuard.` appear?

**Comment by bigpresh** [comment] 2019-03-12 16:36
Also, please see #484 which it sounds on quick reading like this may be a duplicate of; if it is indeed the same issue, then place admin claims as a workaround for now until the next release which contains a fix, according to #484.

**Comment by bigpresh** [comment] 2019-03-12 16:40
Er, when I say "the next release" it sounds like I mean 16.11.6 which according to the [16.11.6 release notes](https://github.com/TechFortress/GriefPrevention/releases/tag/16.11.6) contains a fix for WorldGuard integration from PR #457.

So, yeah, please try GP 16.11.6 and let us know if it works for you?

**Comment by ShawnPR1** [comment] 2019-03-12 17:06
Thanks for the quick reply! Will go through the logs now to ensure it's hooked to WorldGuard. Will also test GP 16.11.6 in a few minutes if WorldGuard is indeed hooked.

WorldGuard has been hooked successfully upon looking at the log. Will update GP to 16.11.6 and get back to this thread in a few minutes

**Comment by ShawnPR1** [comment] 2019-03-12 17:26
Version 16.11.6 has fixed this entire issue.

Players can not claim any land in a region they cannot build in.

I would like to, however, request that players not be able to set the first claim corner at all and be immediately notified of not being able to claim land. Just a simple request seeing as right now they only get notified they can't claim land there when they set the last corner of their claim.

Sorry for not using the latest version in the first place, but at least I know the issue is indeed resolved.

**Comment by bigpresh** [comment] 2019-03-12 20:06
Good to hear it's solved!  I'll close this ticket, but feel free to raise a new one as a feature request for an immediate warning on the first click.  It would seem to make sense, and shouldn't be massively difficult to implement.

**Closed as completed by bigpresh** 2019-03-12 20:06 UTC
