### ISSUE TITLE
Can't create new claims or resize already existing claims in 1.12

### ISSUE THREAD

**Issue by LizC864** [GriefPrevention/GriefPrevention#151] opened 2017-06-19 03:25 UTC
### What behaviour is expected:
Expected to claim new area or expand existing claimed area
### What behaviour is observed:
Diamond block for 1st claimed corner appears, nothing appearing at 2nd corner when right clicked with a gold shovel. Same for trying to expand a claim. On right-clicking original corner, it acknowledges that corner is to be moved, but when 2nd block is right-clicked, nothing happens.
### Steps/models to reproduce:
Right click 1st corner or corner of an already existing claim, right click 2nd corner to create new claim or new block in order to resize claim.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-ede465d-bb4ae3b (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
GriefPrevention version 16.7.1

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):

Citizens
CoreProtect_2.13.1
Dynmap-Essentials-0.91
Enchanted Furnace
EssentialsX-2.0.1
GriefPrevention
MCLib
OnTime
RandomTeleport
VPNGuard
Vault
XrayInformer
dynmap-2.5
worldedit-bukkit-6.1.2
worldguard-6.1.2

**Comment by RoboMWM** [comment] 2017-06-19 03:31
Hmm, nothing in console or anything? Can you try with just GP installed?

**Comment by LizC864** [comment] 2017-06-19 03:35
Found this in the console:
[CC] Starting process.
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:218) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:343) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:210) ~[?:?]
	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:464) ~[?:?]
	at com.sk89q.worldguard.bukkit.permission.AbstractPermissionModel.hasPluginPermission(AbstractPermissionModel.java:45) ~[?:?]
	at com.sk89q.worldguard.bukkit.permission.RegionPermissionModel.mayIgnoreRegionProtection(RegionPermissionModel.java:42) ~[?:?]
	at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:29) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:845) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.resizeClaim(DataStore.java:1184) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.resizeClaimWithChecks(DataStore.java:1291) ~[?:?]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2205) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12-1297.jar:git-Spigot-ede465d-bb4ae3b]
	... 17 more

**Comment by RoboMWM** [comment] 2017-06-19 03:36
Aha. Update WorldGuard.

**Comment by RoboMWM** [comment] 2017-06-19 03:37
Duplicate of #147. 

On that ticket:

> Let me know if updating WorldGuard fixes the issue.

**Comment by LizC864** [comment] 2017-06-19 03:40
I just deleted WorldGuard & it works fine now. Thank you! :)

**Comment by RoboMWM** [comment] 2017-06-19 03:40
Lol ok, that'll do too :P

**Closed as completed** 2017-06-19 03:39 UTC
