### ISSUE TITLE
Tog-able MobGriefing like /claimexplosions 

### ISSUE THREAD

**Issue by Royster-85** [GriefPrevention/GriefPrevention#413] opened 2018-11-15 00:07 UTC
Is it possible to add a setting/command where claim owners can toggle the ability to enable mob griefing on their claims, similar to how /claimexplosions works?

Thanks

Royster

**Comment by RoboMWM** [comment] 2018-11-15 00:32
Duplicate of #72

**Closed as completed by RoboMWM** 2018-11-15 00:32 UTC
