### ISSUE TITLE
Not support on 1.13

### ISSUE THREAD

**Issue by Ghost-chu** [GriefPrevention/GriefPrevention#326] opened 2018-07-27 01:48 UTC
GP not complete support on 1.13

**Comment by Ghost-chu** [comment] 2018-07-27 01:59
[09:55:48 INFO]: [GriefPrevention] FXRiz placed suspicious WATER_BUCKET @ w2: x-458, z944
[09:55:51 INFO]: wang_daifu issued server command: /spawn
[09:56:00 WARN]: [GriefPrevention] Plugin GriefPrevention v16.7.1 generated an exception while executing task 236533
java.lang.NoSuchFieldError: BEACHES
at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:800) ~[?:?]
at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:44) ~[?:?]
at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:27) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[Ghostchu_Main.jar:git-Spigot-0b44fa0-1ef1ffd]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Ghostchu_Main.jar:git-Spigot-0b44fa0-1ef1ffd]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by RoboMWM** [comment] 2018-07-27 06:02
It does except for the auto extend task. Duplicate of #319

**Closed as completed by RoboMWM** 2018-07-27 06:02 UTC
