### ISSUE TITLE
Server refusing to start up with missing dependencies.

### ISSUE THREAD

**Issue by thighholder** [GriefPrevention/GriefPrevention#2009] opened 2023-02-19 17:35 UTC
### Observed Behavior

Server refusing to startup due to "Grief Prevention" missing dependencies

### Expected Behavior

Server refusing to startup due to this issue.

### Reproduction steps

First time posting on github so not sure what this section is??

### Stack trace or error log

```shell
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies detected!
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] You have a plugin that is depending on a plugin which refers back to that plugin. Your server will shut down until these are resolved, or the strategy is changed.
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies:
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] GriefPrevention depends on TheUnderground depends on GriefPrevention...
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
```

### Server version

```shell
Paper 1.19.3
```

### GriefPrevention version

```shell
16.18
```

### Configuration

```yaml
(unable to as server wont start on Exaroton so I cannot retrieve any files)
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by RagingBeast** [comment] 2023-02-19 18:25
Having the same issue here. Was working perfectly well for a few days before.

**Comment by fisher60** [comment] 2023-02-19 18:44
Also having this issue while attempting to re-build a docker container with minecraft 1.19.3, did not update GriefPrevention plugin, did not update minecraft server. Attempted rollback to previous version of server, none build.

**Comment by Novasky-Guy** [comment] 2023-02-19 19:20
This issue just started occuring for me aswell. Was working absolutely fine not even 2 hours ago. as for 

**Reproduction steps**:

Step 1: Put Griefdefender in the plugins folder of a Paper 1.19.3 (Latest version) server
Step 2: Launch the server
Step 3: It doesnt work and you will have to force kill the server.

**Comment by kribjo** [comment] 2023-02-19 20:19
I ran into the same issue. Following the suggested workaround (adding the java option -Dpaper.useLegacyPluginLoading=true) seems to fix it for me. 
NB - I do not use any plugin called "TheUnderground", and have never done so. I don't even know what it is.... I have no idea why this warning suddenly appears.

**Comment by bigpresh** [comment] 2023-02-19 20:45
I *suspect* this is down to changes in PaperMC/Paper#8108 which is in Paper 1.19.3 build 405, released today, see in particular [this comment](https://github.com/PaperMC/Paper/pull/8108#issuecomment-1179867016)

As far as I can see this can only have started happening because people have updated to that Paper build (or later) - maybe not intentionally, maybe they have some auto-update thing enabled.

`TheUnderground` is a `softdepend` in our plugin.yml, so I'm not sure it ought to be triggering this...

The suggested workaround `-Dpaper.useLegacyPluginLoading=true` sounds reasonable for now for those affected for now; I think this should be run by the Paper devs to see if they think that a plugin that `softdepends` on another plugin that in turn depends on it should be considered a circular dependency or not - I don't think it should personally.

**Comment by kribjo** [comment] 2023-02-19 20:59
I definitely updated my Paper build just before this happened, I am running git-Paper-406. I understand the idea of avoiding circular dependencies, and I am happy that there is a simple workaround.
The reference to the "TheUnderground" plugin which I definitely never have had on my server still confuses me though, if this actually was a dependency issue I think it would be bigger issue that I don't have it at all on my server. :)

**Comment by bigpresh** [comment] 2023-02-19 21:13
It's entirely possible that we can fix this by just removing the softdepend on `TheUnderground` entirely - I'm not familiar with it but it _looks_ to be a closed source plugin that only supports up to MC 1.10:

https://blackspigot.com/downloads/the-underground-5-7-with-ewg-6-34-1-7-10-1-8-1-9-1-10.517/

... so there's little point in current GP versions that won't work on MC versions that ancient bothering to softdepend on it.  According to that link above it's only ever had 297 downloads, so it doesn't seem very widely used.

We already removed it from `loadbefore` back in 6d0a1b97c4100862243a - but I don't think that change has reached a released version yet.

It was originally added to `softdepend` in 935fc53bed1200c all the way back in 2014.

I think I've rather convinced myself that we should just remove the softdep.... I'll raise a quick PR for that and gather opinions there :)

**Comment by Machine-Maker** [comment] 2023-02-19 21:27
This was already fixed afaik, a new version wasn't released. Fixed in https://github.com/TechFortress/GriefPrevention/pull/1912

**Comment by RagingBeast** [comment] 2023-02-19 21:50
Following the changes on #1912 and #2010, I edited the plugin.yml file inside the .jar file and it worked!

Open .jar using WinRar (or whatever you have), edit the plugin.yml file and remove "TheUnderground, " from the softdepend line and remove line "loadbefore: [TheUnderground]".

**Comment by thighholder** [comment] 2023-02-19 22:21
@RagingBeast  this worked for me! Little work around for any issues. This is happening in other plugins too, not just this! Thank you for everyone working so fast on it

**Comment by SmotheryAbyss** [comment] 2023-02-20 09:20
> I ran into the same issue. Following the suggested workaround (adding the java option -Dpaper.useLegacyPluginLoading=true) seems to fix it for me. NB - I do not use any plugin called "TheUnderground", and have never done so. I don't even know what it is.... I have no idea why this warning suddenly appears.

Which file did you add the line to, kind of a newbie with plugins and servers So I can't figure it out

**Comment by bigpresh** [comment] 2023-02-20 09:29
>> I ran into the same issue. Following the suggested workaround (adding the java option -Dpaper.useLegacyPluginLoading=true) seems to fix it for me.

> Which file did you add the line to,

Wherever you set the Java options for launching Minecraft depends on how you start & manage your MC server - if you use a host with a control panel there's probably somewhere you can set Java invocation command-line options or flags.  It'd be alongside various other settings like `-Xms`, `-Xmx`, `-XX:+DisableExplicitGC`, `-XX:+UseG1GC` `-Dusing.aikars.flags=mcflags.emc.gs` and similar things.

If you can't find that, following @RagingBeast's suggestion to edit the `plugin.yml` file within the plugin `.jar` would also do the job.

**Comment by Geolykt** [comment] 2023-02-20 10:16
I have talked with Robo about this issue and they said that they would publish a build once the needed testing is done. Let's hope that this issue won't haunt the users for all too long!

**Comment by kribjo** [comment] 2023-02-20 10:53
> Which file did you add the line to, kind of a newbie with plugins and servers So I can't figure it out

I run my own server so I added it to the command line I use for starting it. Note that it has to go *before* the "-jar" part.

Example server starting line with only the workaround argument added:
java -Dpaper.useLegacyPluginLoading=true -jar paper-1.19.3-406.jar

It is very likely that you already have some java arguments in that line, then it could end up looking similar to this after adding the workaround argument:
java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dpaper.useLegacyPluginLoading=true -jar paper-1.19.3-406.jar --nogui

This might all be different if you are using a server hosting service or if you are using more complex scripts to manage the server.

**Closed as completed** 2023-02-20 17:52 UTC
