### ISSUE TITLE
Cannot resize claims after reaching max number of claims

### ISSUE THREAD

**Issue by Spoonerj1** [GriefPrevention/GriefPrevention#1210] opened 2021-01-15 23:45 UTC
### What happened:
Player attempted to resize claim, but couldn't because they have the max number of claims per player. 

### What was expected:
Easily resizing a claim, per normal behavior of the plugin.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. make claims until reaching the max number of claims per player (whatever is set in config)
2. resize one of the claims
3. see the error stating the max claims has been reached.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  Paper 1.16.14 R0.1-Snapshot
Paste of `/version GriefPrevention`: GP 16.16.0

### Stack trace/error or server log
N/A

```yml

attached

```
[config.txt](https://github.com/TechFortress/GriefPrevention/files/5823422/config.txt)

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment] 2021-01-15 23:48
resizing calls the new claim method, and although part of it has been separated for the separate events, it sounds like it's still coupled together pretty tightly. This probably will be changed in either v18 or v19.

**Comment by Spoonerj1** [comment] 2021-01-15 23:49
So the only solution is to delete a claim to stay under the limit?

**Comment by Jikoo** [comment] 2021-12-06 22:52
Oddly enough, not sure how this would be possible. I checked into it because I'm touching some event-related stuff and I remembered this, but the message is only sent while using a shovel or command to create a new claim. The logic is pretty messy and I didn't spend a long time looking over it, but it looks like resize initiation should never hit the only place the claims limitations are sent.

This is the shovel-related one, and it's only sent if the player is attempting to start a new corner, not when they complete a resize.

https://github.com/TechFortress/GriefPrevention/blob/a7cb4a0c788436f9808acbb831627a282fde4744/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L2529

**Comment by Jikoo** [comment] 2024-03-15 17:12
Not able to reproduce this. Resizing with shovel and `/extendclaim` both work while at claim limit. Creation is blocked as expected for both shovel and `/createclaim`. 
![image](https://github.com/GriefPrevention/GriefPrevention/assets/1353270/cfaee4df-3a7e-43a9-953e-64566316b7b6)
Given the age (and age before I looked into it the first time, it was nearly a year old by then) I'm going to close this. If it's still an issue, happy to reopen, just let us know the reproduction steps.

**Closed as not planned by Jikoo** 2024-03-15 17:12 UTC
Labels: 🚫Cannot Reproduce
