### ISSUE TITLE
You can use glow ink sacks on signs in other peoples claims

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#1649] opened 2021-11-05 19:03 UTC
### Observed Behavior

If you right click a sign in a claim with a glow ink sack, it makes the text glow

### Expected Behavior

Dont do this

### Reproduction steps

1. Have someone claim a sign
2. Right click it with glow ink sack

### Server version

```shell
This server is running Airplane version git-Airplane-98 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 655e853 on HEAD)
You are running 4 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Airplane-54 (MC: 1.17.1)
```

### GriefPrevention version

```shell
16.17.1-2b69191
```

### Configuration

```yaml
Unneeded for the issue
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-11-05 21:44
Duplicate of #1457

**Closed as completed by Jikoo** 2021-11-05 21:44 UTC
