### ISSUE TITLE
Beaches produce a NoSuchFieldError

### ISSUE THREAD

**Issue by writeescape** [GriefPrevention/GriefPrevention#365] opened 2018-09-04 15:20 UTC
### What behaviour is observed:
Created a Claim over a beach
### What behaviour is expected:
comes back with: java.long.NoSuchFieldError: Beaches
### Steps/models to reproduce:
Claim a beach it will throw the error

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Grief Prevention: 16.8
Minecraft: 1.13.1

### Stack trace/error

```
java.lang.NoSuchFieldError: BEACHES
	at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:800) ~[?:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:46) ~[?:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-x-latest.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-x-latest.jar:git-Spigot-2440e18-4228a56]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by RoboMWM** [comment] 2018-09-04 17:43
Duplicate of #319

**Closed as completed by RoboMWM** 2018-09-04 17:43 UTC
