### ISSUE TITLE
Villagers griefed

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GriefPrevention/GriefPrevention#1203] opened 2021-01-14 19:33 UTC
### What happened:
_What you saw_
Villagers turned to Witches in claims
### What was expected:
_What you expected to see_
Villagers being intact in claims
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1. Set weather to thunder
2. Step 2. Use channeling trident 
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
This server is running Paper version git-Paper-394 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: 
: GriefPrevention version 16.16.0
### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment] 2021-01-14 20:18
what, this happens when another player who isn't trusted does this? Does lightning strike? ????

**Comment by RoboMWM** [comment] 2021-01-14 20:18
also, missing the `/version` stuff

**Comment by TDMidkwhatisxd** [comment] 2021-01-14 20:22
yes ... now i just locked the weather

**Comment by TDMidkwhatisxd** [comment] 2021-01-14 20:23
Just now i updated my issue , pasted everything
Edit: The trident does not damage, but when there is thunderstorm, channeling make villagers witches.
Edit Again: thx for fast reply 👍

**Comment by RoboMWM** [comment] 2021-01-14 20:37
I know we stop fire, since apparently fire is called before the lightning event. Is there an event that's called when villagers are transformed? Hmm..

**Comment by TDMidkwhatisxd** [comment] 2021-01-14 21:02
Maybe event lightning is being called even if fire is canceled

**Comment by Jikoo** [comment] 2021-01-14 23:57
[EntityTransformEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityTransformEvent.html) should be called. I don't believe the lightning is actively prevented, only the fire.

**Comment by TDMidkwhatisxd** [comment] 2021-01-15 08:21
So, this is going to be hard to fix.

**Comment by RoboMWM** [comment] 2021-01-15 17:57
Ok that's what I figured, that it wouldn't identify the source entity. Ugh.

Should we try to just cancel the lightning strike? Seems like no matter which thing we stop it's gonna be a hacky fix.

**Comment by Jikoo** [comment] 2021-01-15 22:02
I feel like cancelling the lightning strike is the way to go. We shouldn't have to hack around to make sure that blocks aren't ignited or entities aren't changed if the lightning doesn't hit in the first place. I believe getting the trident requires a bit of hacky location work, but it contains the workaround to a single place instead of spread across multiple events. We probably still need some damage handling to prevent indirect PVP - builders should probably still be able to use lightning - but that does greatly reduce GP's responsibility. It prevents a lot of edge cases, and if any do still exist they'd probably be bugs on Spigot's end instead.

Should consider extracting projectile ownership determination to a helper utility, it's a relatively large source of duplicate code if memory serves.

**Comment by Jikoo** [comment] 2021-01-15 22:05
The only thing I can see upsetting people about lightning cancellation is some kind of admin-claimed PVP arena... not sure what a good fix for that would be. An addon could take care of it, but there're also a couple of config options for PVP in claims.

**Comment by RoboMWM** [comment] 2021-01-15 22:36
> We shouldn't have to hack around to make sure that blocks aren't ignited

Block ignition happens before the lightning is called iirc.

**Comment by TDMidkwhatisxd** [comment] 2021-01-15 23:29
just block lightning and add a option in config to disable it, if some admins dont like it.

**Comment by RoboMWM** [comment] 2021-01-19 17:16
duplicate of #1125

Since no conclusion has been reached here, let's move further comments to the first-reported issue.

**Closed as completed by RoboMWM** 2021-01-19 17:16 UTC
