### ISSUE TITLE
Messages are the other way round? :S + /gpreload does not work?

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#190] opened 2017-08-14 18:26 UTC
### What behaviour is expected:
Messages in the good order
/gpreload reloading messages.yml
### What behaviour is observed:
/claimlist messages are the other way round, investegating a claim with a stick, /trustlist
/gpreload does not reload messages.yml (I made sure its valid YAML and can say for 100% it is.)
### Steps/models to reproduce:
Type /claimlist, /trustlist, or investegate a claim with your stick
Add some modifications to messages.yml and do /gpreload

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Paper version git-Paper-1188 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
GP 16.7.1

### Stack trace/error (if applicable)

```
-----
```

### GriefPrevention config.yml (if applicable)

```yml
-----
```

### Plugin list (if applicable):
-----

**Comment by RoboMWM** [comment] 2017-08-14 19:26
Two separate issues, one of which is a duplicate of #85 

As for /gpreload, it doesn't reload everything. Just some of the things in the config.

**Closed as completed by RoboMWM** 2017-08-14 19:26 UTC
