### ISSUE TITLE
Grief Prevention admin area break/place blocks players can do

### ISSUE THREAD

**Issue by VICHulkFamilyTV** [GriefPrevention/GriefPrevention#1368] opened 2021-05-17 21:32 UTC
### What happened:
Hello, I have tried everything. I have taken out every plugin except Grief Prevention.

### What was expected:
Players can break/place blocks in the admin area

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/Version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Spigot 1.16.5
Paste of `/version GriefPrevention`:  16.17.1-2b69191 

### Stack trace/error or server log

Paste entire stack trace right here inside these backticks.

https://paste.revivenode.com/jexezacevu

Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Disabled
      world: Survival
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 1200
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 50.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):
Anvil Color
AureliumSkills-Alpha1.6.8
BeehivesPro
BKCommonLib-1.16.5-v2
Celeste-1.51
ChairsPlus
Citizens
CitizensHologram
Clearlag
ColoredSigns
CommandNPC-1.9.1
CoreProtect-19.5
CrazyAuctions.v1.2.16
CrazyEnchantments.v1.8-Dev-Build-v9
DragonSlayer_0.10.6_Jeppa
DragonTimer_1.5.2
EditableSign-7.0.4
EntityTrackerFixer
EssentialsX-2.18.2.1
EssentialsXChat-2.18.2.1
EssentialsXProtect-2.18.2.1
EssentialsXSpawn-2.18.2.1
ExoticGarden - DEV 76 (git d148a)
FireWorkMaker
Floristics-2.5.1-1.15
GriefPrevention
Harbor-1.6.3
HologramsPlaceholders-2.7-SNAPSHOT
HolographicExtension-1.10.9
HyperDrive
Jobs4.17.1
MoreOres
Multiverse-Core-4.2.2
OhTheDungeon
PlaceholderAPI-2.10.9
Scoreboard-revision
sellstick-1.0-SNAPSHOT
SetHome-5.1.2
SetTheSpawn
Shop
ShukerBoxBackPacks
SkillsPro-18.12.1.2.1
Slimefun4 - DEV 902 (git 14c91)
SwimmingHorses
SybHideAndSeek
TAB v2.8.10
Towny-0.96.3.0
TownyChat-0.81
TownyNameUpdater-5.0
TrainCarts-1.16.5-v1-843
UltimateKits-2.6.16
UltraPermissions
Vault
ViaVersion-3.2.1
worldedit-bukkit-7.2.5-dist

### Debugging steps attempted

- [ x ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ x ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ x ]  I attempted running only GriefPrevention on the server
  - [ x ] Issue still occurs even if GriefPrevention is the only plugin running
- [ x ] I attempted testing for the issue on a new server
  - [ x ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment] 2021-05-17 21:58
When you say you've tried everything - what have you tried?

What happens when players try to build there (what message do they get?) and what did you expect?

I'd imagine it's one of two things:

* you've created an admin claim (using /adminclaims) and players can't build in it because they don't have trust - that's correct behaviour.  You can trust individual players with `/trust playername`, or trust everyone with `/trust public`.  (You've not indicated that you have done anything to give trust)
* you're close to the world spawn point, and the server's `spawn-protection` setting in server.properties is stopping them from building there.

Those are just guesses as there's not enough info to know yet.

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 22:04
I have tried what I could to fix it but had no luck. this server is still being set up.  what I have an issue with is that if you, not an op player can still break/place blocks no matter what. you do not get an error message Grief Prevention is the only plugin in right now and nothing else. all other plugins have been pulled

**Comment by bigpresh** [comment] 2021-05-17 22:32
OK, I'm confused.  You said that you expect that "Players can break/place blocks in the admin area"

* is the admin area you're referring to an admin claim (i.e. created with /adminclaims on)?
* if you right click in that area with a stick, does GP tell you about the claim?
* and for clarity: are you finding that players *can* place blocks when you expect them not to be able to, or that they *can't* and you want them to be able to?

Note that if you have the `griefprevention.adminclaims` permission then you can build in admin claims, even if there's no specific trust entry for you.

As for "can still break/place blocks no matter what. you do not get an error message" - you'd only expect a message if GriefPrevention *prevents* you from placing/breaking a block - it obviously doesn't say anything if you're allowed to, as that would be extremely spammy :)

Please try to describe in more detail what you've done, what behaviour you're expecting and what you're seeing, as I must admit I'm confused at the moment.

**Comment by RoboMWM** [comment] 2021-05-17 22:37
> What happened:
> Hello, I have tried everything. I have taken out every plugin except Grief Prevention.

So, um, what's the issue?

I highly recommend reading the template more carefully/redoing the issue report and not deleting formatting marks such as backticks. It seems you've kind of butchered it and ignored key sections.

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 22:40
ok the issue Grief Prevention is not working right players can break blocks and replace them and you get no error in the admin claim

**Comment by RoboMWM** [comment] 2021-05-17 22:44
Ok in that case we need a paste of the server.log which is what the template requested.

**Comment by RoboMWM** [comment] 2021-05-17 22:46
Ok a paste of the full server.log is requested not a portion of it. Thanks.
Also, can you paste the contents of your admin claim file (see griefpreventiondata/claimdata folder)

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 22:46
[latest.log](https://github.com/TechFortress/GriefPrevention/files/6497261/latest.log)
sorry i did not load this

**Comment by RoboMWM** [comment] 2021-05-17 22:53
Please provide the contents of both of the claims with the claimdata folder.

This is potentially a duplicate of another issue that I'll need to search up, but that issue had far more information than this one.

**Comment by RoboMWM** [comment] 2021-05-17 22:58
~~Potentially related: #83, #170~~

**Comment by RoboMWM** [comment] 2021-05-17 22:59
Either way, please provide the contents of both of those claim files, this might provide a clue as to what may be causing this issue.

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 22:59
0.yml
Lesser Boundary Corner: world;-624;0;-101
Greater Boundary Corner: world;17;0;821
Owner: ''
Builders:
- public
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false

1.yml
Lesser Boundary Corner: world;1103;69;-322
Greater Boundary Corner: world;1111;74;-314
Owner: fb5e8b8a-709a-48c9-a8d2-2beaf8bb351b
Builders: []
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false

2.yml
Lesser Boundary Corner: world;-95;63;275
Greater Boundary Corner: world;-88;64;277
Owner: ''
Builders: []
Containers: []
Accessors: []
Managers: []
Parent Claim ID: 0
inheritNothing: false

**Comment by RoboMWM** [comment] 2021-05-17 23:04
Ok, your admin claim has `/trust public` which means everyone will be able to build in there...

This information is also available in-game via /trustlist. Note that all subclaims inherit the parent claim's trustees by default.

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 23:06
TY how do i fix that?

**Comment by RoboMWM** [comment] 2021-05-17 23:06
`/untrust public`

**Closed as completed by RoboMWM** 2021-05-17 23:06 UTC
Labels: 🚫Invalid, 🚫Not a GP issue

**Comment by VICHulkFamilyTV** [comment] 2021-05-17 23:08
[23:07:35] [Server thread/INFO]: /UnTrust <player> this what I'm getting when I put command in
