### ISSUE TITLE
Players can use Splash/Lingering Potions of Poison to damage/kill animals/villagers/players in another player's claim

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GriefPrevention/GriefPrevention#1370] opened 2021-05-26 18:55 UTC
### What happened:
Players can use Splash/Lingering Potions of Poison to damage/kill animals/villagers/players in another player's claim

### What was expected:
GP to prevent a player from doing damage to animals/villagers/players inside other player's claims

### Steps to reproduce:
1. Make a claim
2. Put an animal/villager/player inside it
3. Have a player that does not own the claim throw a Splash/Lingering Potion of Poison at the animal/villager/player inside the claim

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Tuinity-"1222573" (MC: 1.16.5)
Paste of `/version GriefPrevention`: GriefPrevention version 16.17.1-2b69191

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment] 2021-05-28 18:43
is this a duplicate

**Comment by Jikoo** [comment] 2021-05-28 23:01
Duplicate of #782

**Closed as completed by Jikoo** 2021-05-28 23:01 UTC
