### ISSUE TITLE
Not Fixed previous time.

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#37] opened 2016-11-09 13:09 UTC
Players Still dont get claim blocks.

I created 2 "BasePerms"

Baseperms: Have the negative permssions for claims.

Baseperms2: **Dont** have the negative permissions for claims.

But ranks that are "Inheritance" with Baseperms2: still dont get any claim blocks.

Permissions: http://pastebin.com/DQUkif1h

Can you not just add permissions to all commands? That they are not default granted to everyone. (So that we dont need to use the negative permissions)

**Comment by RoboMWM** [comment] 2016-11-10 02:25
Half of this is a duplicate of #28, if you have an issue, comment there instead of making another ticket...

> Can you not just add permissions to all commands? That they are not default granted to everyone. (So that we dont need to use the negative permissions)

Most servers rely on default permissions being given to users. Nearly every plugin works this way.

Also, please follow the issue format - I need debug logging to confirm players aren't getting claim blocks (which you can enable in the config).

**Closed as completed by RoboMWM** 2016-11-10 02:25 UTC
Labels: 🚫Not a GP issue
