### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by Yukylyu** [GriefPrevention/GriefPrevention#342] opened 2018-08-04 14:28 UTC
Hi I have this error in 1.13  
When a player wants to make a claim

https://pastebin.com/2PbVcW5d

**Comment by RoboMWM** [comment] 2018-08-05 00:53
Duplicate of #319

**Comment by RoboMWM** [comment] 2018-08-05 00:54
Stupid mobile site can't delete but I guessed and that's not the correct issue this is a duplicate of. If someone can link the correct one that'd be appreciated.

**Comment by Jikoo** [comment] 2018-08-05 04:08
#329 and #332

**Comment by RoboMWM** [comment] 2018-08-05 13:28
Duplicate of #329

Thanks Jikoo

**Closed as completed by RoboMWM** 2018-08-05 13:28 UTC
