### ISSUE TITLE
[Suggestion]: Llamas are horses too

### ISSUE THREAD

**Issue by P0Pss** [GriefPrevention/GriefPrevention#136] opened 2017-05-26 06:50 UTC
Great plugin, one issue I have with it is that when all the pet and creature protection is off llamas are still protected with /givepet and cant be leaded or ridden if you don't own the pet but they can still be damaged. Well, a fix to this would to treat llamas the same way you would horses, another would be to have to option of disabling /givepet entirely. You also can't allow horse sharing without disabling both creature and pet protection.
Thanks.

**Comment by RoboMWM** [comment] 2017-05-26 17:26
Um, whether they can be damaged is linked with the pvp rules. The same applies to wolves and horses.

**Comment by P0Pss** [comment] 2017-05-26 22:30
The problem isn't the damage, the problem is that only one person can ride a llama without having to /givepet inbetween, only the owner can access their chest and use a lead on them.

**Comment by RoboMWM** [comment] 2017-05-27 05:21
Um, I'm confused, what's the issue? Iirc, anyone can ride llamas as there is no "owner" iirc (they're already tamed, yes?)

**Comment by P0Pss** [comment] 2017-05-27 08:43
The problem is that as soon as someone tames the llama they become the owner, how do you let multiple people have access to riding that llama? When I try to ride a llama which someone else has tamed it says "That belongs to {name} until it's given to you with /GivePet." if the llama is "given" to me then the previous owner cant ride it.

**Comment by RoboMWM** [comment] 2017-05-27 17:20
Is PvP enabled in that world, and what are the PvP rules set for it?

**Comment by P0Pss** [comment] 2017-05-27 18:17
Disabled for all worlds, but there is a plugin called PvPManager so you can toggle pvp

**Comment by RoboMWM** [comment] 2017-05-27 18:36
So, PvP is disabled - ok, so it must be using the PvE rules, which would make sense as to why it's restricting who can ride the llama.

**Comment by P0Pss** [comment] 2017-05-27 19:42
The link to the config is https://hastebin.com/udumuqifeq.php could you have a look and tell me what should be changed?

**Comment by P0Pss** [comment] 2017-05-30 15:58
@RoboMWM Have you managed to look at the config?

**Comment by RoboMWM** [comment] 2017-05-30 16:58
You disabled PvP rules in all your worlds, and iirc, GP handles this by applying PvE rules. I think I already mentioned this in another ticket - if not, then definitely in the spigot discussion thread. As for why - well, ask Big_Scary - that's what he told me.

See refactoring discussion ticket for changes.

**Comment by P0Pss** [comment] 2017-05-30 17:22
This doesn't make sense, the problem has nothing to with pvp/pve or any damage at all. I'm gonna rephrase it.

My friend can't ride my Llama.

**Comment by RoboMWM** [comment] 2017-05-31 03:20
> GP handles this by applying PvE rules. 

But he can ride horses?

Hmm..

**Comment by P0Pss** [comment] 2017-05-31 08:06
Yes, horses is not a problem, just the Llamas, and recently found out donkeys have the same problem

**Comment by RoboMWM** [comment] 2017-05-31 22:37
Just noticed you're missing GP and server /version which you deleted from the issue template.

**Comment by P0Pss** [comment] 2017-06-01 14:26
Paper Build 1103 (1.11.2)
GriefPrevention 16.6

**Comment by RoboMWM** [comment] 2017-06-01 16:58
Try 16.7.1. Think there was a change regarding horses in that.

**Comment by RoboMWM** [comment] 2017-06-01 17:00
Potentially a duplicate of #93

**Comment by RoboMWM** [comment] 2017-07-01 05:42
Any update on this?

**Comment by P0Pss** [comment] 2017-07-01 09:26
Oh yes sorry, I completely forgot about this thread, turns out the server owner didnt update the plugin cause he didnt think there were any major changes :/
Thanks for the help!

**Comment by RoboMWM** [comment] 2017-07-01 16:57
Ok, assuming fixed then.

**Closed as completed by RoboMWM** 2017-07-01 16:57 UTC
Labels: Need more info
