### ISSUE TITLE
Bukkit/Spigot EventException: Could not pass event PlayerJoinEvent to GriefPrevention v15.3 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by jeanmarin** [GriefPrevention/GriefPrevention#23] opened 2016-10-08 17:01 UTC
### What behaviour is expected:

_What you expected to see_
GP not working,
### What behaviour is observed:

[19:25:43 ERROR]: Could not pass event PlayerJoinEvent to GriefPrevention v15.3 org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[Spigot.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[Spigot.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [Spigot.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java
:333) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [Spig
ot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144)
 [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54)
 [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:23
3) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.jav
a:140) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
827) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [Spigot.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [Spigot.jar:git-Spigot-570526c-75a8885]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.setPortalCooldo
wn(I)V
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerJoin(Playe
rEventHandler.java:766) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[Spigot.jar:git-Spigot-570526c-75a8885]
        ... 14 more
### Steps/models to reproduce:

_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_
Player Logs in, during Player post. OnPlayerJoin event
### Spigot/Craftbukkit/Paper and GriefPrevention version:

**_This can be found by running `/version` and `/version GriefPrevention` on your server.**_
GriefPrevention V15.3
### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```
### GriefPrevention config.yml (if applicable)

``` yml
Paste config inside here
```
### Plugin list (if applicable):

Plugins (26): AutoMessage (2.5.5), ChestRestock (2.3-
b70), DropProtect (0.3), dynmap (2.3-1142), Dynmap-WorldGuard (0.90), Essentials
 (TeamCity), EssentialsAntiBuild (TeamCity), EssentialsChat (TeamCity), Essentia
lsProtect (TeamCity), EssentialsSpawn (TeamCity), GAListener (1.3.2), GriefPreve
ntion (15.3), HolographicDisplays (2.2.1), Multiverse-Core (2.5-b717), Multivers
e-Portals (2.5-b725), NoCheatPlus (3.15.0-SNAPSHOT-sMD5NET-b1022), NoSwear (7.1)
, OrePlus (1.1.1), PermissionsEx (1.23.4), PlugMan (2.1.1), RandomTeleport (mave
n-version-number), Vault (1.5.6-b49), Votifier (1.9), WorldBorder (1.8.6), World
Edit (5.5.8), WorldGuard (6.1.2;e38d98d)

**Comment by jeanmarin** [comment] 2016-10-08 17:02
Spigot Version
[13:01:46 INFO]: This server is running CraftBukkit version git-Spigot-570526c-7
5a8885 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[13:01:46 INFO]: Checking version, please wait...
[13:01:47 INFO]: You are 6 version(s) behind

**Comment by RoboMWM** [comment] 2016-10-08 18:05
You didn't read the update notes.

Duplicate of #16

**Closed as completed by RoboMWM** 2016-10-08 18:05 UTC
Labels: 🚫Invalid

**Comment by jeanmarin** [comment] 2016-10-08 18:25
Sorry about that no I did not see #16
