### ISSUE TITLE
ExpandClaim doesnt work if you are below Y=0

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#1936] opened 2022-08-23 22:37 UTC
### Observed Behavior

If you are below Y=0 on 1.18+ worlds, you cannt use /expandclaim. It tells you that you must be inside a claim (even though the area is protected)

### Expected Behavior

It should expand

### Reproduction steps

1. Claim an area
2. Go below Y=0 in the claim
3. Try to expand

### Server version

```shell
This server is running Pufferfish version git-Pufferfish-11 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a593bf6 on HEAD)
You are running 22 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-71 (MC: 1.18.2)
```

### GriefPrevention version

```shell
16.17.1
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: 319
    world_nether: -1
    world_the_end: -1
    spawn: -1
    Creative: -1
    pvp: -1
    resource_world: -1
    ultra_end: -1
  Claims:
    Mode:
      world_the_end: Disabled
      spawn: Disabled
      Creative: Disabled
      pvp: Disabled
      ultra_end: Disabled
      world: Survival
      resource_world: Disabled
      world_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 150
    Max Accrued Claim Blocks:
      Default: 200000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 400
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -65
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: -1
      AllClaims:
        DaysInactive: 365
        ExceptWhenOwnerHasTotalClaimBlocks: 2000
        ExceptWhenOwnerHasBonusClaimBlocks: 2000
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome;/espawner;/changems;/essentials:;/echangems;/mobspawner;/emobspawner;/spawner;/aa;/AdvancedArmorStands;/advancedarmorstands:aa
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: '[]'
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      spawn: false
      Creative: false
      pvp: false
      resource_world: false
      ultra_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 25000000
    ClaimBlocksPurchaseCost: 1.0
    ClaimBlocksSellValue: 1.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by DarkKingKaan** [comment] 2022-08-28 08:22
Correct me if I'm wrong, but I'm pretty sure that you can expand a claim downwards by simply placing a block under the claim. It should work as long as you are the owner of it.

**Comment by JHarris12345** [comment] 2022-08-28 11:06
> Correct me if I'm wrong, but I'm pretty sure that you can expand a claim downwards by simply placing a block under the claim. It should work as long as you are the owner of it.

Thats not the issue. Claims already stretch from bedrock to max height. The issue is you cannot explain the claim in any direction if you are standing below Y0

**Comment by DarkKingKaan** [comment] 2022-08-28 11:54
> Thats not the issue. Claims already stretch from bedrock to max height. The issue is you cannot explain the claim in any direction if you are standing below Y0

Oh, sorry. I thought you meant expanding just vertically. I'll do some testing to see if it's the case on my server as well.

**Comment by Jikoo** [comment] 2022-08-29 16:48
Please reproduce on 16.18.

**Comment by bipedd** [comment] 2022-09-10 19:40
I've tried this on 16.18 on paper 1.19.2, this issue still persists.

**Comment by MrButtersDEV** [comment] 2022-10-16 19:54
I can confirm this is still an issue on 1.19.2 v16.18

**Comment by MrButtersDEV** [comment] 2022-10-16 20:20
> I can confirm this is still an issue on 1.19.2 v16.18

Seems that claims never extended below y=0. I fixed it by updating the spigot maven import from 1.17 to 1.19.2

https://github.com/MrButtersDEV/GriefPrevention/releases/tag/16.18

**Comment by Jikoo** [comment] 2024-03-15 17:20
Still unable to reproduce this, /extendclaim even works while at a Y level not actually included in the claim yet because it hasn't expanded. My assumption is that this was indirectly resolved by max depth settings or auto-extension changes, because there has been change to claim fetching in the command since its introduction in 2015.

**Closed as not planned by Jikoo** 2024-03-15 17:20 UTC
