### ISSUE TITLE
dupe Shulker Box and Unlimited bullets

### ISSUE THREAD

**Issue by taka1945** [GriefPrevention/GriefPrevention#1428] opened 2021-06-23 09:32 UTC
### What happened:
in protect area 

### What was expected:
dupe Shulker Box

1. Step 1. owner place a Shulker Box
2. Step 2. friend  mine it no broken but it  give a Shulker Box

Unlimited bullets

1.Step 1. right hand Firework Rocket
2.Step 2. left hand bullets
you got Unlimited bullets ....

### Server and GriefPrevention version:
spigot 1.17 3160

### Plugin list (if applicable):
16.17.1

**Comment by Jikoo** [comment] 2021-06-23 17:15
Sounds like a plugin with a bad integration. Cannot reproduce. Please fill out the template sections you deleted.

You can try to track it down by removing half your plugins at a time or you can try to use EventDebug.

**Comment by bigpresh** [comment] 2021-09-03 13:54
No further info provided so I think we're safe to close this for now, there's nothing further we can do with it unless more details are provided (in which case we can happily re-open).

**Closed as completed by bigpresh** 2021-09-03 13:54 UTC
Labels: 🚫Invalid, 🚫Cannot Reproduce
