### ISSUE TITLE
Lecturn

### ISSUE THREAD

**Issue by junsteed** [GriefPrevention/GriefPrevention#578] opened 2019-08-05 10:44 UTC
Hi, 1.14.4 here, there's a thing with the Lectern.
Right now players can read & take book from lectern only in ContainerTust (but cannot place back)

Players we're hoping to have...
AccessTrust to read book on lectern.
and ContainerTrust to take and put back book.
so they can make restaurants or some museum and shit. Thanks

**Comment by ShaneBeee** [comment] 2019-08-05 21:12
This has already been mentioned in #537

**Comment by RoboMWM** [comment] 2019-08-06 00:53
Duplicate of #537

**Closed as completed by RoboMWM** 2019-08-06 00:53 UTC
