### ISSUE TITLE
Breeding not working in claims?

### ISSUE THREAD

**Issue by itzWebby1** [GriefPrevention/GriefPrevention#854] opened 2020-06-14 22:34 UTC
Villagers and mobs won't breed within claimed land. I have looked around for an answer on this before posting here but I have not found one. Ty in advance.

**Comment by bigpresh** [comment] 2020-06-24 19:21
Did you find anything out?

Can you be more specific - are we talking about a player breeding a mob e.g. feeding items to mobs to make them breed, or spontaneous breeding e.g. villagers with sufficient food items on them, in the bounds of a village with a population cap higher than the population cap never randomly entering breeding mode?  I'm pretty sure GP doesn't have anything to do with that.

Also, do you have any other plugins installed which could be interfering?

**Comment by itzWebby1** [comment] 2020-06-24 20:23
It's all breeding. As soon as the mobs gets moved from the claim or the
claim gets abandoned, breeding works fine.

**Comment by RoboMWM** [comment] 2020-06-25 03:39
well, if you think this is a bug, then please create a new issue and fill out the bug report template. I know mobs breed for sure. Idk why villagers would be treated any differently. So ya.

**Comment by Jikoo** [comment] 2020-08-01 12:51
Sounds like a duplicate of #922. If GP is removing entities, you'll see logs or a message.

**Closed as completed by Jikoo** 2020-08-01 12:51 UTC
Labels: 🚫Invalid
