### ISSUE TITLE
GriefPrevention Placeholders

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#928] opened 2020-08-02 09:03 UTC
### What happened:
[PlaceholderAPI] griefprevention is attempting to register placeholders via a PlaceholderHook class which is no longer supported!

### What was expected:
That placholders would work with the latest stable PlaceholderAPI v 2.10.8

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Start server with PlaceholderAPI v 2.10.8 (https://www.spigotmc.org/resources/placeholderapi.6245/updates)
2. Execute `papi ecloud download griefprevention` (in order to get the latest expansion)
3. Execute: `papi reload` / restart server
4. See console for warnings
5. See in game that GP placeholders aren't working

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper 1.16.1
Paste of `/version GriefPrevention`: 16.14.0
Version of Expansion-griefprevention: 1.4.0

### Stack trace/error or server log
```
[10:53:06 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[10:53:06 INFO]: [PlaceholderAPI] Fetching available expansion information...
[10:53:06 INFO]: [PlaceholderAPI] Successfully registered expansion: bungee
[10:53:06 INFO]: [PlaceholderAPI] Successfully registered expansion: pinger
[10:53:06 INFO]: [PlaceholderAPI] Successfully registered expansion: server
[10:53:06 WARN]: [PlaceholderAPI] griefprevention is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
[10:53:06 INFO]: [PlaceholderAPI] Successfully registered expansion: vault
```

Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml
default

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server (no cuz it's the combination of papi and GP)
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running  (it's the combination of papi and GP)
- [X] I attempted testing for the issue on a new server
  - [X] Issue still occurs even after testing on a new server

**Comment by Jikoo** [comment] 2020-08-02 12:15
Duplicate of #923

**Closed as completed by Jikoo** 2020-08-02 12:15 UTC
Labels: 🚫Not a GP issue
