### ISSUE TITLE
Still Not Loading

### ISSUE THREAD

**Issue by zlarr** [GriefPrevention/GriefPrevention#830] opened 2020-05-26 03:46 UTC
### What happened:
I've checked for extra jar files and I'm still getting this error. Im running the server normally.
![pluginerror](https://user-images.githubusercontent.com/65933500/82858144-da843780-9ec7-11ea-87bf-cdaf6d75a559.PNG)

### What was expected:
The plugin should generate a folder and run, which it did when I first got the plugin but not anymore.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
I don't know.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 

This server is running Paper version git-Paper-256 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
--

Paste of `/version GriefPrevention`: 

16.13.0
--

### Stack trace/error or server log

```
[20:36:24 ERROR]: Could not load 'plugins\GriefPrevention (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:140) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:359) ~[patched_1.15.2.jar:git-Paper-256]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-256]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-256]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:203) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-256]
        at me.ryanhamshire.GriefPrevention.GriefPrevention.<init>(GriefPrevention.java:71) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[patched_1.15.2.jar:git-Paper-256]
        ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:206) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-256]
        at com.github.hornta.wild.WildPlugin.<init>(WildPlugin.java:29) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:336) ~[patched_1.15.2.jar:git-Paper-256]
        ... 4 more

```

Or, paste the server.log at gist.github.com and paste the link here: 
<script src="https://gist.github.com/zlarr/83f9f5884a098b8bd326385929010bc1.js"></script>
### GriefPrevention config.yml

```yml

Unavailable

```

### Plugin list (if applicable):
AdvancedAchievements, AdvancedEnchantments*, AreaShop, ArmorStandTools, BeastWithdraw, DisablePlayerHunger, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, ExtraContexts*, Factions, HolographicDisplays, HolographicExtension, Jobs, LuckPerms, mcMMO, MultiChat*, Multiverse-Core*, MythicMobs, OldCombatMechanics, PL-Hide, PlaceholderAPI, ProtocolLib, ServerNPC, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, SimpleBackup*, TAB, UltimateKits, UltimateStacker, UltraCustomizer, UltraCustomizerPlus, Vault, ViaVersion*, Votifier, Wild, WorldEdit, WorldGuard

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment] 2020-05-26 04:30
Looks like your pasting stuff in the wrong places still. Paste your stuff on fresh new lines.

**Comment by RoboMWM** [comment] 2020-05-26 04:31
Also, we're going to need the entire server log. Please paste the contents of `latest.log` in gist and paste the link here: https://gist.github.com

**Comment by zlarr** [comment] 2020-05-26 04:50
Done

**Comment by zlarr** [comment] 2020-05-26 04:57
It works when its the only plugin enabled

**Comment by Jikoo** [comment] 2020-05-26 05:56
Duplicate of #798. The wild plugin you are using improperly shaded the entirety of GP. Either use a different wild plugin or seek an updated build of it.

**Closed as completed by Jikoo** 2020-05-26 05:56 UTC
Labels: 🚫Not a GP issue

**Comment by zlarr** [comment] 2020-05-26 06:20
thanks
