### ISSUE TITLE
Some players suddenly unable to claim within WorldGuard region

### ISSUE THREAD

**Issue by s1h4d0w** [GriefPrevention/GriefPrevention#627] opened 2019-09-21 19:00 UTC
### What happened:

- Our 20k x 20k world has 4 regions covering the outer 3000 blocks of the world where pvp is enabled (see image below).
- The \_\_global\_\_ region has one flag: `pvp deny`
- These outer pvp regions have a priority of 1000 and flags `pvp allow` and `passthrough allow`
- Some random players are suddenly unable to claim within these regions, while they were able to before
- They either receive a `You can't claim all of this because you're not allowed to build here.` or a `You don't have permission to build there, so you can't claim that area.` which is the region overlap error, but there are no regions aside of the pvp region, they are not near the border of the region, and they were able to claim just fine earlier.
- So for example, player has a claim within this pvp region, they use the golden shovel to resize the claim 1 block, well within the region and their left over claim blocks, but they get the error `You can't claim all of this because you're not allowed to build here`. They fly to a random part within the pvp region and do `/claim` and they get the `You don't have permission to build there, so you can't claim that area.` error, while they **do** have permission to build there and there are not other claims/regions near them.
- I have `CreationRequiresWorldGuardBuildPermission: true` in my config, but the region is set to `passthrough allow` so the players should have permission to build. Maybe it's an issue with that?

**IMPORTANT:** This only happens for some players, now 3 out of the ~50 that play on my server

Approximation of world:
![image](https://user-images.githubusercontent.com/5654654/65380039-129d0000-dcd3-11e9-80e2-a132cdd9e50c.png)

### What you expected:
Them to be able to claim

### Steps to reproduce:
See above

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.12.0-d4d7ac4

### Stack trace/error or server log

```
No errors or output in console related to this
```

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival: -1
    survival_nether: -1
    survival_the_end: -1
  Claims:
    Mode:
      survival_nether: Disabled
      survival_the_end: Disabled
      survival: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 400
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 10
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival: true
      survival_nether: true
      survival_the_end: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp;/trapped
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 150.0
    ClaimBlocksSellValue: 50.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### Plugin list (if applicable):

AdvancedAchievements, AntiCurse, ArmoredElytra*, AuthMe, AutoMessager, AutoRestart, BetterRTP*, ChatReaction, ChopTree2, ClearLag, ConsoleSpamFix, CoreProtect, CrazyEnchantments, CustomPolls*, DeathCoordinates, DynamicShop, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, GriefPrevention, HolographicDisplays, InfernalMobs, Item2Chat, JetsSellChests, Jobs, JoinMessagePlus*, JukeBox, KeepDeathDrop*, LuckPerms, Matrix, MineableSpawners, Multiverse-Core, MyCommand, NoteBlockAPI, OnTime*, Parkour, PhantomSMP, ProtocolLib, QuickShop, RestrictedCreative, ServerListPlus*, SkinsRestorer, StackMob, SuperbVote, TradeSystem, UltraCosmetics, Vault, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

**Comment by RoboMWM** [comment] 2019-09-29 23:57
I'd really like to see reproduction steps because I don't really get what the issue is (the bottom line). The bullet points feels like a bunch of information blobbed together with no organization (some are context, some are output, some are scenarios).

Regardless, WorldGuard is being dropped from v20 so that it's responsibility falls upon an addon, which is what should be the case.

**Comment by Jikoo** [comment] 2019-09-30 00:13
Not sure what the functional difference between build and passthrough is, but it may be worth noting that GP checks WG's build flag, not passthrough.

If it's consistent and specific to a particular set of players, it sounds like a permissions or region group issue.
Try finding a player who cannot claim in a region and use them to debug. Is it just the one region? Is it all of them? Compare their permissions to a player who can claim. If it's a specific region, check the region's settings.

**Comment by RoboMWM** [comment] 2019-09-30 00:31
GP should be checking passthrough then. I'm pretty sure most people who use worldguard erroneously use the build flag despite it's message about it (though tbh, idk why they can't just make their "build" flag what the "passthrough" flag is and change whatever "build" is to something else).

**Comment by s1h4d0w** [comment] 2019-09-30 16:31
Good to hear thanks, I'll try setting the build flag in those areas and see if it fixes the issue. I used passthrough because it basically means "inherit building rights from other regions" and they explained that it was to be used for zones where you just want to apply a few flags like pvp and not mess with building rights. I was afraid of allowing building, as I didn't know if it would mess with other things, plus if I'd need to set a load of other flags like container access, interacting with buttons, etc.

The weird thing is that it works perfectly fine for 99% of players on my server, just now 6-7 players who have this issue. I assumed it was just maybe some race condition permission wise.

**Comment by Jikoo** [comment] 2020-12-11 13:52
Closing in favor of #1140 - WG appears to be working fine, but ideally compatibility will be handled by an addon in the future.

**Closed as completed by Jikoo** 2020-12-11 13:52 UTC
