### ISSUE TITLE
Config option to take height into account only for subdivide claims

### ISSUE THREAD

**Issue by YanisBft** [GriefPrevention/GriefPrevention#973] opened 2020-08-16 21:31 UTC
In order to make subdivide claims even more useful, I think it would be nice to be able to take height into account for subdivide claims only. As a server owner, someone suggested it to create apartments in a building for instance.

There no real alternatives right now, as you can only take height into account for all claims, not just subclaims.

**Comment by Jikoo** [comment] 2020-08-16 21:55
Duplicate of #269

**Closed as completed by Jikoo** 2020-08-16 21:55 UTC
