### ISSUE TITLE
Paper watchdog error + crash

### ISSUE THREAD

**Issue by MithrandirCraft** [GriefPrevention/GriefPrevention#908] opened 2020-07-26 02:34 UTC
https://gist.github.com/MithrandirCraft/1e209e38ec435424d8232612529d0328

Paper: git-Paper-114 (MC: 1.16.1)
GP: 16.14.0

**Comment by Jikoo** [comment] 2020-07-26 03:00
Duplicate of #889 
Downgrade paper or use a build without the light task priority change patch.

**Closed as completed by Jikoo** 2020-07-26 03:00 UTC
