### ISSUE TITLE
Possibly claim block duplication bug

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#195] opened 2017-08-24 01:03 UTC
An admin of mine sent me this email, thought I'd share it with you:

I've found a fatal flaw in the way that GriefPrevention allows transferring blocks. This allows you to basically have infinite claim blocks. It does require two players. Here's how to replicate it.
1.Player A creates a large claim and transfers the claim to player B. Player A regains their claim blocks after transferring
2. Player B logs out and logs back in. This resets their claim block account from a negative number to 0.
3.Player B is able to abandon the claim and receive the claim blocks from the claim. This gives them a positive number. By using this glitch, Player A will get their claim blocks back and Player B will receive a large amount of claim blocks for free.

https://youtu.be/M2LDjGPGkWw

You're also able to blow up the sides of someone's plot if they have Claimexplosions enabled. Simply place a TNT block one block outside of the person's claim and light it. It will blow things up inside their claim.(edited)

https://youtu.be/0D1EC6hhFvE

**Comment by RoboMWM** [comment] 2017-08-24 02:19
> Player A creates a large claim and transfers the claim to player B

Normal players cannot use the /transfer command... it's an administrative command.

> You're also able to blow up the sides of someone's plot if they have Claimexplosions enabled.

Expected behavior. Only in some cases are TNT able to be tracked by the player who ignited it (i.e. they specifically used flint and steel). Hence why a player has to specifically execute this command, and it is temporary (i.e. resets when player logs out).

**Comment by RoboMWM** [comment] 2017-08-24 08:05
Since it seems this is more of an "fyi" than a report I'm going to close this; though let me know if you want to "resolve" these "issues."

Otherwise, just pass a link to this issue to them so they are aware and resolve some misunderstandings.

**Closed as completed by RoboMWM** 2017-08-24 08:05 UTC
