### ISSUE TITLE
Official localization

### ISSUE THREAD

**Issue by Dum4G** [GriefPrevention/GriefPrevention#1133] opened 2020-12-07 17:25 UTC
I think v20 should be officially bundled with different messages.yml translated by community efforts and locale set to the system one, so we didn't have to search for proper translations over and over again.

As of quality concerns I suggest going to Crowdin platform as it's free for OSS projects and is leading in terms of usability. This way more people will be capable of doing localizations without messing with yaml files and each term or best variants will be decided by actual players

**Comment by Jikoo** [comment] 2020-12-07 19:17
Duplicate of #705

**Closed as completed by Jikoo** 2020-12-07 19:17 UTC
