### ISSUE TITLE
Fire from lightning can be used to damage animals in claim

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#532] opened 2019-05-19 02:04 UTC
### What happened:
Farm animals harmed by channeling effect, ignoring land claims.

### What you expected:
Farm animals protected by the land claim.

### Steps to reproduce:
Have someone create a land claim which protects farm animals (pigs, sheep..)
Create a thunderstorm (/thunder true). 
Hit the animal with a trident that's enchanted with channeling.

### Server and GriefPrevention version:

Paper version git-Paper-624 (MC: 1.13.2)
GriefPrevention version 16.11.6

### GriefPrevention config.yml

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 2
    MinimumArea: 4
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_AXE
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 2147483647
        ExceptWhenOwnerHasBonusClaimBlocks: 2147483647
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 10
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 100.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 6
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: false
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 365
  Abridged Logs:
    Days To Keep: 14
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

**Comment by RoboMWM** [comment] 2019-05-26 22:18
Are they harmed by the effect, or the lightning? https://github.com/TechFortress/GriefPrevention/pull/417 should've prevented lightning damage

**Comment by NullCase** [comment] 2019-05-28 22:28
i don't know. 

Tridents on their own don't harm the animals. tridents with channeling but without lightning storms don't harm animals.

its just when tridents trigger lightning strikes that animals are harmed.

**Comment by NullCase** [comment] 2019-05-28 22:30
channeling does cause lightning strikes inside land claims, which shouldn't be possible if #417 is correct.

maybe i'm missing something or something has changed.

**Comment by RoboMWM** [comment] 2019-06-09 18:22
does lightning also cause entities to be set on fire?

**Comment by NullCase** [comment] 2019-06-10 05:54
The land is set on fire but the entities are not.

OK, it looks like the land being on fire is the cause of animal harm. Animals never are set on fire but take damage once the land is set on fire from the Channeling/Trident.

![2019-06-10_01 51 09](https://user-images.githubusercontent.com/32785664/59175104-438d6680-8b22-11e9-9128-15f4afc585e8.png)
![2019-06-10_01 51 16](https://user-images.githubusercontent.com/32785664/59175112-47b98400-8b22-11e9-8c11-97cc1387c8d8.png)

**Comment by RoboMWM** [comment] 2019-06-13 01:28
That PR should've also stopped blocks from being from lightning caused by tridents. So I guess it's debug time to see if the entity passed in BlockIgniteEvent is indeed the same entity that is passed in LightningStrikeEvent...

**Comment by RoboMWM** [comment] 2019-06-14 04:04
Hmm, there is an EntityCombustByEntityEvent. Are you sure the block is ignited? or just the entity.

**Comment by RoboMWM** [comment] 2019-06-14 04:06
It seems that lightning **only** occurs if an entity is struck by the trident. I thought it was wherever the trident landed...

**Comment by RoboMWM** [comment] 2019-06-14 07:42
```
[02:38:20] [Server thread/INFO]: [EventDebug] Event fired: EntityDamageByEntityEvent
getDamager: CraftTrident
isCancelled: false
getDamage: 8.0
getFinalDamage: 8.0
getCause: PROJECTILE
getEntityType: COW
getEntity: CraftCow
[02:38:20] [Server thread/INFO]: [EventDebug] Event fired: BlockIgniteEvent
getIgnitingEntity: CraftLightningStrike
isCancelled: false
getCause: LIGHTNING
getBlock: AIR at Location{world=CraftWorld{name=cityworld},x=-111.0,y=80.0,z=1155.0,pitch=0.0,yaw=0.0}
[02:38:20] [Server thread/INFO]: [EventDebug] Event fired: LightningStrikeEvent
getLightning: CraftLightningStrike
isCancelled: false
getCause: TRIDENT
getWorld: CraftWorld{name=cityworld}
[02:38:20] [Server thread/INFO]: [EventDebug] Event fired: EntityCombustByEntityEvent
getCombuster: CraftLightningStrike
getDuration: 8
isCancelled: false
getEntityType: COW
getEntity: CraftCow
```

**Comment by RoboMWM** [comment] 2019-06-14 07:46
So, `BlockIgniteEvent` for some reason is fired before before `LightningStrikeEvent.` So that's great. I guess we'll just block that event if lightning is the cause in claims I guess.

**Closed as completed** 2019-06-14 07:50 UTC

**Comment by NullCase** [comment] 2019-06-15 06:45
it looks solved. perfect.

normal lightning still harms animals but tridents do not.
