### ISSUE TITLE
error when player joining

### ISSUE THREAD

**Issue by vetsku** [GriefPrevention/GriefPrevention#32] opened 2016-10-23 10:39 UTC
version 15.3 java8. all the default settings, plugin works great but when player joins it shows some errors, doesnt affect anything :)

[13:36:52] [User Authenticator #1/INFO]: UUID of player Vetskuuuu is 2648d3e5-43a2-466b-b3f6-ce74cd956bb3
[13:36:52] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to GriefPrevention v15.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.setPortalCooldown(I)V
    at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerJoin(PlayerEventHandler.java:766) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-90f61bc-83a9dbd]
    ... 14 more

**Comment by RoboMWM** [comment] 2016-10-23 12:01
You didn't read the update notes.

Duplicate of https://github.com/TechFortress/GriefPrevention/issues/16

**Closed as completed by RoboMWM** 2016-10-23 12:01 UTC
