### ISSUE TITLE
Split griefprevention.eavesdrop permission into 2. 1 for softmute and one for whispers.

### ISSUE THREAD

**Issue by markusew** [GriefPrevention/GriefPrevention#1074] opened 2020-10-26 16:01 UTC
I would like to be able to split the griefprevention.eavesdrop permission into 2 cause I want one rank to be able to see softmuted people without being able to see whispers. 

Another potential solution would be the ability to disable the whisper spying altogether and use essentials social spy for example. But I didn't see any way to disable this in the config. Ty!

**Comment by Jikoo** [comment] 2020-10-26 16:24
Duplicate of #38

**Closed as completed by Jikoo** 2020-10-26 16:24 UTC
