### ISSUE TITLE
Not aible to claim

### ISSUE THREAD

**Issue by Brabus453** [GriefPrevention/GriefPrevention#994] opened 2020-09-04 16:16 UTC
Hi

I installed the plugin, but we are unable to claim any land.

it keeps saying go to oposit corner... but when we do, it does not work.

**Comment by bigpresh** [comment] 2020-09-04 16:25
More details.  What actually happens?  "it does not work" gives us next to nothing to go on.

What GP version are you using, on which Minecraft version, etc?

Does anything appear in your server logs?

i.e. all the info that's asked for by the template that comes up if you use the "bug report" option when raising a ticket, https://github.com/TechFortress/GriefPrevention/issues/new?template=bug-report.md

**Comment by Brabus453** [comment] 2020-09-04 16:42
sorry about that. it is latest version. (16.14.0)

on spigot 1.16.2 

nothing in logs. (no log files)

when i claim, i use gold shovel, bleu box appears, i go to other corner, same thing, blue box, and it says go to opposit corner... but it does not claim the land

only messages i can find, is in console at boot and seems fine:

[18:46:50] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.14.0
[18:46:50] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[18:46:50] [Server thread/INFO]: [GriefPrevention] 0 total claims loaded.
[18:46:51] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[18:46:51] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[18:46:51] [Server thread/INFO]: [GriefPrevention] Boot finished.

but no log files in GP and also no PlayerData

**Comment by RoboMWM** [comment] 2020-09-07 11:07
Ya gonna need more info. Please make a [new issue](https://github.com/TechFortress/GriefPrevention/issues/new/choose) and choose the bug report template.

**Comment by Jikoo** [comment] 2020-10-08 15:41
Looks like a duplicate of #1022. Closing since Robo requested a new issue anyway.

**Closed as completed by Jikoo** 2020-10-08 15:41 UTC
Labels: Need more info, 🚫Invalid
