### ISSUE TITLE
3 Dimensional Claiming

### ISSUE THREAD

**Issue by httpelliott** [GriefPrevention/GriefPrevention#710] opened 2020-02-01 17:19 UTC
**As** a player/ server owner
**I want** to be able to make 3 dimensional claims
**Because** it allows for more complex claiming and prevents griefing in subdivisions and when giving out permissions to many   ##players.

Optional questions:

**Is your feature request related to a problem? Please describe.**
When trying to make something on a server like a building you rent out rooms to people, any rooms that are vertically above another will give the permissions you give people to all the floors above and below. This means people would be able to go to the room above them and grief/steal etc. Considering this plugin is meant to protect against all greif, it's not doing that in this case.
Another example is wanting to make a public farming area, that is below a base. In order to allow people access to use the farm, i would be giving them access to break anything in my base above.

**Describe alternatives you've considered**
Make claiming 2D by default, so the same as it is now. But add a /3dclaims command, which allows you to toggle 3d claiming mode. In this mode you would select one corner at the y level you want to be the bottom of the claim, and then the other corner you would want to be the top. 
It would be similar to how you use the wand in worldedit.
The /3dclaims toggle would work the same as /subdivideclaims, and untoggle when you take the shovel out of hand.

Ive seen claims in this plugin that are 3D already. Ive been mining and when going up i hit a claim that only comes down a few blocks on the y axis, rather than all the way to bedrock, as a result of some sort of bug when unclaiming/resizing.
This shows that 3D claiming would be possible, and I hope it can be implemented soon.
Thank you for your time :)

**Comment by RoboMWM** [comment] 2020-02-01 19:03
Duplicate of #269

**Closed as completed by RoboMWM** 2020-02-01 19:03 UTC

**Comment by httpelliott** [comment] 2020-02-03 12:40
Sorry for creating a duplicate.
So is this not possible because of performance issues or just because you feel it would break away from the simplicity and player-use side of the plugin?
If you make it require a toggle like I suggested I don't see how it can really make the plugin become too complex. Only people who know about the command would ever have to use it, and it would only be needed in subclaims.
If it's due to performance issues then I understand.
Is there any addons out there that implement a subclaim 3d toggle you know of?

**Comment by RoboMWM** [comment] 2020-02-04 01:08
You can repost this as a comment in #269 since yours uses the new format.

> So is this not possible because of performance issues or just because you feel it would break away from the simplicity and player-use side of the plugin?

Three reasons, in short:

1. Would require an overhaul of the claim system. This heavily ties into the other point - simplicity. This includes overlap checks and other things that I don't recall offhand. Basically, this is an expensive feature request that would not be primarily used in this plugin. (I also have quite a number of comments on how GP has become "bloated" and "offers too much," which considering BigScary's design intent, I do agree to some extent. It certainly is messy enough wading through the code.)
1. Simplicity - how would this be visualized? I have yet to find a good way to perform this, if it's even possible without client mods. Also, I'm not sure how to make it easy to set or adjust height. Sure, if the player is familiar with WorldEdit's //wand this is a no-brainer - and could be one of many potential options.
1. Performance: Not so much for player actions, but for more intensive stuff such as pistons - which fire a lot of events depending on what's going on in your server. Even now it's still an issue for some servers that an option to disable this check entirely has been added via a PR.

That being said, I have no issues with it being an addon - especially since there are many ways one could perform height management or visualization (particles, fake glass blocks, structure blocks, etc.). I'm also trying to work on v20 which would make it easier to add these features, but I don't seem to see much interest in testing such.
