### ISSUE TITLE
Players loosing ClaimBlocks randomly

### ISSUE THREAD

**Issue by flashbtw** [GriefPrevention/GriefPrevention#1599] opened 2021-09-26 15:01 UTC
Claimblocks (Bonus) are randomly disappearing. My players have Claims, having a certain amount of claimblocks needed. 
(for example, someone has a claim 520 blocks big and another claim 300 blocks big. Now, if the issue is occurring, the player only has the amount of Claimblocks needed for the claim(s). All in the accrued claimblocks. So he has 820 accrued but no bonus claimblocks although he had some before.)

I use the newest version of GP, and have a external MySQL Server. (Root Server, i7 4770, 32 Gigs RAM, 240GB SSD (yes there is tons of space left), stable Connection, otherwise all of my other Inventory, PlayerDataBridge, etc. Plugins would not function properly) 

Not disappearing Claimblocks

1. external MySQL Server 
2. GP 16.17.1

This server is running Paper version git-Paper-232 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7d10cde)
GriefPrevention version 16.17.1-2b69191
### Stack trace/error or server log

no errors

Or, paste the server.log at gist.github.com and paste the link here: 

```yml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
  Claims:
    Mode:
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 150
    Max Accrued Claim Blocks:
      Default: 500000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 50
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 120
        ExceptWhenOwnerHasTotalClaimBlocks: 2500
        ExceptWhenOwnerHasBonusClaimBlocks: 750
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Schreibe nicht in CAPS und spamme nicht! Andernfalls wirst du
      stummgeschaltet.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: jdbc:mysql://censored
    UserName: censored
    Password: censored
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

AdvancedBan, AuthMe, BungeeTabListPlus, CoreProtect, CountdownCommand, EntityDetection, Essentials, EssentialsChat, EssentialsMysqlStorage, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FastLogin, GriefPrevention, Harbor, LPC, LuckPerms, LWC, MysqlInventoryBridge, MysqlPlayerDataBridge, OpenInv, PL-Hide-Pro, ProtocolLib, spark, TimeObserver (my own one, does nothing with GP), Vault, VillagerOptimiser, Votifier, VotingPlugin, VpnControl, WorldGuard

### Debugging steps attempted
Deleting PlayerData1 and ClaimData1 directory
fixNegativClaimblockAmounts: false (not sure if worked)

thx for helping <3

**Comment by flashbtw** [comment] 2021-10-14 19:39
new screenshot showing the problem: https://imgur.com/a/cdAEse2
It happened to me. I had roundabout 1,200,000 Claimblocks left. 

Happened today. Yesterday there was everything fine

**Comment by mfb4** [comment] 2022-01-06 02:02
I have experienced the same (as a player, don't have server insight). No bonus claim blocks involved. The available claim blocks were suddenly reduced to the amount of blocks claimed at that time, i.e. there were 0 unused claim blocks left. From there on it started increasing normally again. Others playing at the same time didn't have any change.

**Comment by Jikoo** [comment] 2022-01-19 17:11
This happens if your SQL server fails to respond - GP defaults to 0 and then corrects claim blocks to the total claim blocks used by all the user's claims. This can only be fixed by a rewrite of the SQL datastore.

Duplicate of #666

**Closed as completed by Jikoo** 2022-01-19 17:11 UTC

**Comment by flashbtw** [comment] 2022-01-19 18:40
So, If I understood (#)666 correctly, the problem just occurs when I'm idling 8 hours long at my server, the connection doesn't do anything and it eventually will time out. Is there a variable in my SQL config for fixing it, without breaking any other SQL tasks?
According to your comment, I need to rewrite the SQL Datastore. I didn't find any information about a SQL Datastore or just Datastore (just NoSQL was recommended). I would really appreciate it if you could help me with this.

I'm looking forward to your answer!

**Comment by Jikoo** [comment] 2022-01-19 19:18
So that depends on the actual error. If you're seeing specifically the timeout error in your logs prior to claim block loss, follow the bandaid steps in https://github.com/TechFortress/GriefPrevention/issues/1312#issuecomment-799470630 to increase wait timeout.

The reason I linked that particular issue is that Nouish does a good job of explaining why claim blocks are deleted. Tl;dr is that GP's SQL usage is just bad. Essentially GP always overwrites the data in the database no matter what should actually be occurring, and the way it does so is even more prone to data loss.
