### ISSUE TITLE
Glow item frames aren’t protected

### ISSUE THREAD

**Issue by Sealflipper** [GriefPrevention/GriefPrevention#1487] opened 2021-07-22 17:19 UTC
### What happened:
_What you saw_
Glow item frames in the 1.17 update aren’t protected in grief prevention. People can steal items from them even if they’re untrusted in a claim.
### What was expected:
_What you expected to see_
The item frames are expected to protect the items in them but glow item frames don’t do this.
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!
Just grief prevention in paper 1.17. I understand you don’t have an update for 1.17 out yet, but GP still works for the most part, it just doesn’t work for glow item frames. I’m reporting this ‘bug’ only because I think you were not planning on making a 1.17 update because GP works fine on 1.17. Just wanted to bring this issue up.
### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 
1.17, latest version of GP
### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment] 2021-07-23 10:31
Duplicate of #1435

**Closed as completed by Jikoo** 2021-07-23 10:31 UTC

**Comment by xavierlvll** [comment] 2021-07-29 03:49
Just ran into This Bug, Had somebody steal some netherite tool's from a player on my server and found all the item's in a new guy's inventory, hope this may might help a bit

Have a nice day

**Comment by Jikoo** [comment] 2021-07-29 13:29
@xavierlvll if you look at the ticket that this is a duplicate of you can find instructions for downloading a dev build that has the fix for this.
