### ISSUE TITLE
Moss and Sculk Spread

### ISSUE THREAD

**Issue by GrubLubSnub** [GriefPrevention/GriefPrevention#2334] opened 2024-07-17 21:50 UTC
### Observed Behavior

Untrusted players can spread moss and sculk into claims.

### Expected Behavior

Claims should not allow the spread into the claim (like water and lava)

### Reproduction steps

1. Place moss or sculk catalyst just outside claim.
2. Bonemeal moss or kill a mob next to the sculk.
3. The moss or skulk can spread into the claim

### Server version

```shell
1.21 paper mc
(1.21-882df5bba)
```

### GriefPrevention version

```shell
16.18.4
```

### Configuration

```yaml
Default
```

### Plugin list

```shell
Grief Protection only
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2024-07-18 12:48
Duplicate of #1432

**Closed as not planned by Jikoo** 2024-07-18 12:48 UTC
