### ISSUE TITLE
You can break glow item frames in other claims

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#1726] opened 2021-12-23 18:29 UTC
### Observed Behavior

Untrusted players can break items out of glow item frames in claims

### Expected Behavior

Cant do that

### Reproduction steps

1. Claim land
2. Place glow item frame with item in it
3. Someone else can break it

### Server version

```shell
This server is running Airplane version git-Airplane-110 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 13cdee3 on HEAD)
You are running 2 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Airplane-98 (MC: 1.17.1)
```

### GriefPrevention version

```shell
16.17.1
```

### Configuration

```yaml
https://pastebin.com/ZSKzu7fx
```

### Plugin list

```shell
GriefPrevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-12-24 00:04
Duplicate of #1435

**Closed as completed by Jikoo** 2021-12-24 00:04 UTC

**Comment by Jikoo** [comment] 2021-12-24 00:06
Update to 16.18-RC1 for the fix for this and numerous other issues.

**Comment by JHarris12345** [comment] 2021-12-24 00:26
@Jikoo Where is that

**Comment by Jikoo** [comment] 2021-12-24 00:58
In the releases tab. https://github.com/TechFortress/GriefPrevention/releases
