### ISSUE TITLE
Sweet berry bushes stealing on claims

### ISSUE THREAD

**Issue by LoneDev6** [GriefPrevention/GriefPrevention#556] opened 2019-07-01 09:30 UTC
If you have sweet berry bushes in your claim other people can steal your berry rightclicking on the plant, idk if it's fixable since I didn't find any event regarding this behaviour on spigot docs

This could work I think
![immagine](https://user-images.githubusercontent.com/27242001/60425769-89a28b00-9bf3-11e9-848c-6687570c8434.png)

**Comment by RoboMWM** [comment] 2019-07-01 14:20
Duplicate, but can PR if u wanna

**Comment by RoboMWM** [comment] 2019-07-30 04:52
Duplicate of #548

**Closed as completed by RoboMWM** 2019-07-30 04:52 UTC
