### ISSUE TITLE
Items in glow item frames can be taken out and rotated by those not trusted

### ISSUE THREAD

**Issue by WanderingLemon** [GriefPrevention/GriefPrevention#1453] opened 2021-07-11 19:34 UTC
### What happened:
The items in glow item frames can be rotated as well as removed (not put back in though) by players that don't have trust in a claim or subdivide

### What was expected:
Them to act the same way as regular item frames which don't have the same issue 

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Place down a glow item frame within a claim that you have access to
2. Put an item into that frame
3. Have a player that isn't trusted try to rotate and then remove it from the frame

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `git-Purpur-1262 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)`: 
Paste of `16.17.1-2b69191`: 

### Stack trace/error or server log

```
Nothing in console

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Default

```

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment] 2021-07-11 19:52
Duplicate of #1435

**Closed as completed by Jikoo** 2021-07-11 19:52 UTC
