### ISSUE TITLE
Server hang on player join (getPlayerData)

### ISSUE THREAD

**Issue by MystServer** [GriefPrevention/GriefPrevention#64] opened 2017-01-19 01:05 UTC
----What behavior is expected----
My server doesn't crash

-----What behavior is observed----
My server crashed

----Steps/models to reproduce----
Can't say for certain, it appeared to be random, players were just typing in chat having a conversation. I have an error report here: https://hastebin.com/qokekibopo.rb

----Spigot/Craftbukkit/Paper and GriefPrevention version----
CraftBukkit version: git-Spigot-7d78b81-27dd3ca (MC: 1.11.2)
GreifPrevention version: 16.5

----Stack trace/error (if applicable)----
https://hastebin.com/qokekibopo.rb

**Comment by RoboMWM** [comment] 2017-01-19 01:21
I need more of your log. Try to reproduce if you can.

**Comment by MrArcane** [comment] 2017-01-19 02:04
Here since Robo told me to report it here I will put the error, Robo it's completely random

http://pastebin.com/ybQ4DzZ0

Edit: I just downgraded for now. :p

**Comment by MystServer** [comment] 2017-01-19 02:21
Yeah that's all there was in the log to give you and i can't reproduce it cause i have no idea what caused it. I'm just gonna downgrade for now too.

**Comment by RoboMWM** [comment] 2017-01-19 02:34
@MrArcane your issue is actually different (make a new ticket), and please copy from your server logs, because that stacktrace is all on one line and very hard to read. Also please include more of your log as well.

@MystServer I do actually would like to see more of the log before the watchdog thread dump. It seems yours occurred that someone was joining the server right before it hung, but I can't verify if this is the case without being able to see any more of the log file.

**Comment by RoboMWM** [comment] 2017-01-19 17:25
Also potentially related: https://www.spigotmc.org/threads/griefprevention.35615/page-176#post-2173672

I will need a full server log for any future reports on this issue (I have some ideas about how this is being caused, but will need to see the server log to confirm since I have not been able to reproduce such). Please use a paste service such as http://gist.github.com for pasting the server log

**Comment by RoboMWM** [comment] 2017-01-24 14:30
Appears to be fixed in [16.5.1](https://github.com/TechFortress/GriefPrevention/releases/tag/16.5.1)

**Closed as completed by RoboMWM** 2017-01-24 14:30 UTC
Labels: Need more info
