### ISSUE TITLE
1.18, Console Error while claiming (sometimes)

### ISSUE THREAD

**Issue by Zoro-6191** [GriefPrevention/GriefPrevention#1691] opened 2021-12-04 09:39 UTC
### Observed Behavior

![image](https://user-images.githubusercontent.com/52291201/144704740-f36d190d-9718-4c73-9b1b-7403824a9d7f.png)

### Expected Behavior

shouldnt give error

### Reproduction steps

i have no idea why it happened, I was playing and not observing console. Later checked logs for errors

### Stack trace or error log

```shell
[08:18:53] [Server thread/INFO]: steezy issued server command: /claim
[08:18:53] [Craft Scheduler Thread - 86 - GriefPrevention/WARN]: [GriefPrevention] Plugin GriefPrevention v16.17.1-2b69191 generated an exception while executing task 175466
java.lang.NoSuchFieldError: DESERT_HILLS
	at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:835) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.lambda$getBiomeBlocks$0(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getBiomeBlocks(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:57) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:32) ~[GriefPrevention.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-32]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-32]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Server version

```shell
1.18 Paper #32
```

### GriefPrevention version

```shell
16.17.1
```

### Configuration

```yaml
z
```

### Plugin list

```shell
too long to type
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-12-04 10:15
Duplicate of #1689

**Comment by Jikoo** [comment] 2021-12-04 10:15
Same root cause, if slightly different reproduction

**Closed as completed by Jikoo** 2021-12-04 10:15 UTC
