### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by hotspuraz** [GriefPrevention/GriefPrevention#911] opened 2020-07-27 08:38 UTC
### What happened:
Server is crashing since 1.16.1 and GriefPrevention is in the logs.

https://pastebin.com/Kd3ZNLLE

### Server and GriefPrevention version:

server: 1.16.1
version: 16.14.0

### Stack trace/error or server log

```
[05:41:27] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-110 (MC: 1.16.1) ---
[05:41:27] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[05:41:27] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:27] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[05:41:27] [Paper Watchdog Thread/ERROR]: 49,-129 in 'world:
[05:41:27] [Paper Watchdog Thread/ERROR]: Load Task - none
[05:41:27] [Paper Watchdog Thread/ERROR]: Save Task - none
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[05:41:27] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[05:41:27] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:27] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[05:41:27] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[05:41:27] [Paper Watchdog Thread/ERROR]: 	Stack:
[05:41:27] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.DataStore.getNearbyClaims(DataStore.java:1845)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2026)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$DMH/249634342.invokeVirtual_LL_V(LambdaForm$DMH)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$BMH/1278295085.reinvoke(LambdaForm$BMH)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$MH/894787707.invoke_MT(LambdaForm$MH)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1453)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5296/2140144358.run(Unknown Source)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2948/89143842.run(Unknown Source)
[05:41:27] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[05:41:27] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:27] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[05:41:27] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:31] [Async Chat Thread - #15/INFO]: [Veteran[++] rewub [Nobloet[-] > woah lag
[05:41:32] [Async Chat Thread - #15/INFO]: [GriefPrevention] Muted repeat message.
[05:41:32] [Async Chat Thread - #15/INFO]: [Explorer] aHuncowa [VIP] > hm, if a netherite thingy goes for likr 40k then a netherite scrap 10?
[05:41:32] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-110 (MC: 1.16.1) ---
[05:41:32] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
[05:41:32] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:32] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[05:41:32] [Paper Watchdog Thread/ERROR]: 49,-129 in 'world:
[05:41:32] [Paper Watchdog Thread/ERROR]: Load Task - none
[05:41:32] [Paper Watchdog Thread/ERROR]: Save Task - none
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[05:41:32] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[05:41:32] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:32] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[05:41:32] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[05:41:32] [Paper Watchdog Thread/ERROR]: 	Stack:
[05:41:32] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.DataStore.getNearbyClaims(DataStore.java:1845)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2026)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$DMH/249634342.invokeVirtual_LL_V(LambdaForm$DMH)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$BMH/1278295085.reinvoke(LambdaForm$BMH)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$MH/894787707.invoke_MT(LambdaForm$MH)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1453)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5296/2140144358.run(Unknown Source)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2948/89143842.run(Unknown Source)
[05:41:32] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[05:41:32] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:32] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[05:41:32] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:37] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-110 (MC: 1.16.1) ---
[05:41:37] [Paper Watchdog Thread/ERROR]: The server has not responded for 20 seconds! Creating thread dump
[05:41:37] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:37] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[05:41:37] [Paper Watchdog Thread/ERROR]: 49,-129 in 'world:
[05:41:37] [Paper Watchdog Thread/ERROR]: Load Task - none
[05:41:37] [Paper Watchdog Thread/ERROR]: Save Task - none
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[05:41:37] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[05:41:37] [Paper Watchdog Thread/ERROR]: ------------------------------
[05:41:37] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[05:41:37] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[05:41:37] [Paper Watchdog Thread/ERROR]: 	Stack:
[05:41:37] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.DataStore.getNearbyClaims(DataStore.java:1845)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2026)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$DMH/249634342.invokeVirtual_LL_V(LambdaForm$DMH)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$BMH/1278295085.reinvoke(LambdaForm$BMH)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		java.lang.invoke.LambdaForm$MH/894787707.invoke_MT(LambdaForm$MH)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1453)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5296/2140144358.run(Unknown Source)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2948/89143842.run(Unknown Source)
[05:41:37] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)

```

### GriefPrevention config.yml

```yml

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):
Plugins (49): AdvancedRegionMarket, BuycraftX, ChestShop, ClearLag, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, EasyBackup, Emoji*, EnchantGui, FogusCore, GoldenCrates, GriefPrevention, Harbor, HeadDatabase*, HolographicDisplays, HolographicExtension, Images, Insights, LastLoginAPI, LeaderHeadsRevamped, LiteBans, LuckPerms, MarriageMaster, MineableSpawners, Parties, PL-Hide, PlaceholderAPI, PlayerParticles, PluginConstructorAPI, PremiumVanish, ProtocolLib, Rankup, ShopGUIPlus, SuperLog, SuperTrailsPro*, TAB, UltimateAutoRestart, UltimateTimber, UltraFarm, Vault, Votifier, VotingPlugin, Welcome*, Wild, WorldBorder, WorldEdit, WorldGuard

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by bigpreshkt** [comment] 2020-07-27 08:49
Could be a dupe of #889 and #908 ?  In #889, PaperMC/Paper#3986 was mentioned so could be down to that?

Haven't yet had time to compare the stack trace to see if it appears to be the same problem - but maybe try an older Paper build and see if you still get the issue?  That Paper ticket suggested build 97 could be where the problem started occuring.

**Comment by bigpresh** [comment] 2020-07-27 09:06
Could be a dupe of #889 and #908 ? In #889, PaperMC/Paper#3986 was mentioned so could be down to that?

Haven't yet had time to compare the stack trace to see if it appears to be the same problem - but maybe try an older Paper build and see if you still get the issue? That Paper ticket suggested build 97 could be where the problem started occuring.

**Comment by hotspuraz** [comment] 2020-07-27 09:09
Yeah, I read through the ticket and reverted to paper-88. I ran my test server for a week straight without issue when setting things up and it never crashed. The only differences in the live server is a newer paper version and I started a pre-gen with world border. The pre-gen has been paused and it still crashed though so not sure if that has anything to do with it.

**Comment by Jikoo** [comment] 2020-07-27 11:31
Duplicate of #889 
Also, please do not just tell us "1.16.1" for server version - as you can see from this case, specific build info actually matters.

**Closed as completed by Jikoo** 2020-07-27 11:31 UTC
