### ISSUE TITLE
RestoreNature Sea Level 1 block lower

### ISSUE THREAD

**Issue by ShiftingKill** [GriefPrevention/GriefPrevention#543] opened 2019-06-11 20:19 UTC
### What happened:
/rn
on the ocean, makes the sea level one block lower than usual.

### What you expected:
simply restore nature on some island without the sea level around the island being 1 block lower.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. do /rn
2. get the golden shovel (because /rn doesn't give it?)
3. right click on island near water
4. water blocks are now one level lower than sea level

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: { (paper) | 77<paper<80 }
Paste of `/version GriefPrevention`: 16.11.6

### GriefPrevention config.yml

```yml

Deleted but it was default.

```

To fix this I simply world edited the region with ANY block, not water, and undid it, and then the ocean ran up the island again!

### Plugin list (if applicable):
WorldEdit, WorldGuard, CoreProtect, My custom plugin.

**Comment by RoboMWM** [comment] 2019-06-12 01:23
Duplicate of #535

**Comment by RoboMWM** [comment] 2019-06-12 01:25
This has more details and the actual template, so I'll probably leave this one open instead.

**Closed as completed** 2020-10-24 02:41 UTC
