### ISSUE TITLE
maps broken by non trusted players

### ISSUE THREAD

**Issue by yassinesliti** [GriefPrevention/GriefPrevention#1582] opened 2021-09-13 15:57 UTC
### What happened: so i was building something in my mega base and then sent a tp request to my friend to see if he likes the build or not when he tp'd he saw the map and he was like oh wow that's cool and he punched it with his fists accedently and he broke it he didn't have trust then i was like what the hell and i told him try to shoot it with a bow and he used the bow on it and it broke
_What you saw_ my friend breaking my map without having trust

### What was expected:
_What you expected to see_ i wasen't excpecting it to break

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.make the map
2. Step 2.try breaking it with your fist /bow
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment] 2021-09-13 16:12
What was the map in? I'm going to hazard a guess that it was in a glow item frame, and thus not yet correctly protected?  (but I don't know, because you haven't provided the versions requested)

Otherwise, what does `/trustlist` in the claim say?  Also, was he opped at the time?

**Comment by yassinesliti** [comment] 2021-09-13 18:49
i did use glow item frames and the version was 1.17.1  and he wasen't opped it's a completely survival server  and he also isn't trusted in the claim  he tried breaking a normal block and it didn't work

**Comment by Jikoo** [comment] 2021-09-13 19:30
Duplicate of #1435

**Closed as completed by Jikoo** 2021-09-13 19:30 UTC
