### ISSUE TITLE
/unclaim command produces this error "An internal error occured while attempting to perform this command"

### ISSUE THREAD

**Issue by NotSharwan** [GriefPrevention/GriefPrevention#1689] opened 2021-12-03 10:03 UTC
### Observed Behavior

When a player uses the /claim command to claim an area and then tries to /unclaim it. An error has occurred.
"An internal error occured while attempting to perform this command"
![unknown (3)](https://user-images.githubusercontent.com/48463223/144583009-651350db-9d71-42f8-ae3b-a2e1f3d52ffc.png)

### Expected Behavior

The "An internal error occured while attempting to perform this command" should not appear when using /unclaim of land.

### Reproduction steps

1. claim the land with either claim tool or /claim command.
2. unclaim the land using /unclaim command.
3. An internal error is shown.

### Stack trace or error log

```shell
03.12 04:33:59 [Server]  [GriefPrevention] Plugin GriefPrevention ve559505 generated an exception while executing task 337
03.12 04:33:59 [Server] INFO java.lang.NoSuchFieldError: JUNGLE_HILLS
03.12 04:33:59 [Server] INFO at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.reduceLogs(RestoreNatureProcessingTask.java:286) ~[GriefPrevention.jar:?]
03.12 04:33:59 [Server] INFO at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.run(RestoreNatureProcessingTask.java:143) ~[GriefPrevention.jar:?]
03.12 04:33:59 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-"cfa5b37"]
03.12 04:33:59 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-"cfa5b37"]
03.12 04:33:59 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-"cfa5b37"]
03.12 04:33:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
03.12 04:33:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
03.12 04:33:59 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Server version

```shell
This server is running Paper version git-Paper-"cfa5b37" (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: cfa5b37)
You are running the latest version
Previous version: git-Paper-"956124f" (MC: 1.18)
```

### GriefPrevention version

```shell
GriefPrevention version e559505
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Creative
      world: Creative
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 256
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
Plugins (7): CoreProtect, DiscordSRV, Essentials, GriefPrevention, Parties, WorldEdit, WorldGuard
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-12-03 11:50
Caused by the changes to biomes in 1.18. As a bandaid you can switch to a mode that doesn't do nature restoration on unclaim, `Survival` or `SurvivalRequiringClaims`.

**Comment by LittleBigBug** [comment] 2021-12-03 20:26
You also can't unclaim stuff under y-level 0, but you can claim. I think pistons are wack too

**Comment by Jikoo** [comment] 2021-12-03 20:27
> You also can't unclaim stuff under y-level 0, but you can claim. I think pistons are wack too

Please open a separate issue for separate issues.

**Comment by LittleBigBug** [comment] 2021-12-04 05:15
Sorry, the piston stuff is unrelated but i thought the other was related, I will create other issues!

**Comment by NotSharwan** [comment] 2021-12-04 05:51
I Switched my server to `Survival`, But the error still shows in console.
```
04.12 00:19:02 [Server]  [GriefPrevention] Plugin GriefPrevention ve559505 generated an exception while executing task 53
04.12 00:19:02 [Server] INFO java.lang.NoSuchFieldError: DESERT_HILLS
04.12 00:19:02 [Server] INFO at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:851) ~[GriefPrevention.jar:?]
04.12 00:19:02 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.lambda$getBiomeBlocks$0(AutoExtendClaimTask.java:79) ~[GriefPrevention.jar:?]
04.12 00:19:02 [Server] INFO at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
04.12 00:19:02 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getBiomeBlocks(AutoExtendClaimTask.java:79) ~[GriefPrevention.jar:?]
04.12 00:19:02 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:58) ~[GriefPrevention.jar:?]
04.12 00:19:02 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:33) ~[GriefPrevention.jar:?]
04.12 00:19:02 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-"1f5b013"]
04.12 00:19:02 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-"1f5b013"]
04.12 00:19:02 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-"1f5b013"]
04.12 00:19:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
04.12 00:19:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
04.12 00:19:02 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by flashbtw** [comment] 2021-12-04 06:19
this looks like a biome name not existing anymore because they changed all the names ._.

**Comment by Jikoo** [comment] 2021-12-04 10:19
Automatic claim extension into ground as players build downwards will cause a related console error. You can prevent this by making claims automatically extend all the way to the bottom of the world. Creative claims extend to world depth by default, so that won't be a behavioral inconsistency for you.

**Comment by hetile1** [comment] 2021-12-05 18:22
Not sure this is a dupe or not because it didn't happen on `/unclaim` but on the `/claim` one but on more or less the same issue while player was in creative. Looks to me like this biome name isn't recognized 

```
05.12 12:26:24 [Server] INFO ashleemia issued server command: /adminclaims
05.12 12:26:31 [Server] INFO ashleemia issued server command: /claim
05.12 12:26:31 [Server]  [GriefPrevention] Plugin GriefPrevention v16.17.1-2b69191 generated an exception while executing task 146316
05.12 12:26:31 [Server] INFO java.lang.NoSuchFieldError: DESERT_HILLS
05.12 12:26:31 [Server] INFO at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:835) ~[GriefPrevention.jar:?]
05.12 12:26:31 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.lambda$getBiomeBlocks$0(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
05.12 12:26:31 [Server] INFO at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
05.12 12:26:31 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getBiomeBlocks(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
05.12 12:26:31 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:57) ~[GriefPrevention.jar:?]
05.12 12:26:31 [Server] INFO at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:32) ~[GriefPrevention.jar:?]
05.12 12:26:31 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-"76ee105"]
05.12 12:26:31 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-"76ee105"]
05.12 12:26:31 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-"76ee105"]
05.12 12:26:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
05.12 12:26:31 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
05.12 12:26:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
05.12 12:26:40 [Server] INFO ashleemia issued server command: /adminclaims
```

Server is running papermc 1.18 build #38

**Comment by Jikoo** [comment] 2021-12-05 19:10
@RoboMWM Idk how much you feel like doing manually but I have 8fdbef1f94e9ab81d3e547dcd801b92d0b146e73 that I haven't made a PR for, should resolve this. Not at my PC or I'd do it myself now.

**Comment by braydofficial** [comment] 2021-12-10 08:58
Also having this issue. However, updating the biome names to the new name convention won't fix this for me due to using a datapack that adds custom biomes (no new blocks). Therefore, the names of the biomes generated trough the datapack will also cause errors I guess.

Datapack I'm referring to: https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/

**Question:**
Would it maybe be possible to get rid of the naming structure to make this working even if someone is using custom biomes trough mods or datapacks? -> Not having biome names "hard coded"? This would also make it easier to update the plugin in the future when new biomes are added or when the naming convention will get changed again and would make it more flexible.

**Comment by Jikoo** [comment] 2021-12-10 10:12
The linked PR does decouple GP from the enum, which will ideally eventually lead to a future state where GP uses configurable tags and materials for things like this. That's a ways out and definitely a more advanced feature most users would struggle to configure, so it also has to be a system that self-updates exclusively unmodified values.

**Closed as completed** 2021-12-10 20:06 UTC
Labels: 🐛Bug

**Comment by purejosh** [comment] 2022-01-26 01:25
Someone needs to provide interoperability between GriefProtection and Terralith, and Terralith cannot revert the names of their custom biomes. 

So, why is this closed?

**Comment by Jikoo** [comment] 2022-01-26 01:34
It's closed because it's resolved by the PR that resolved it.

**Comment by purejosh** [comment] 2022-01-26 01:54
When 16.18 releases, this will be addressed, is that correct? Sorry, the documentation isn't user friendly.

**Comment by Jikoo** [comment] 2022-01-26 02:33
[16.18-RC1](https://github.com/TechFortress/GriefPrevention/releases/tag/16.18-RC1) is already tagged as a prerelease. Alternately, (as it has a known issue that has been resolved) the checkbox next to each commit contains a link to that build on the CI.
![image](https://user-images.githubusercontent.com/1353270/151094276-54fd4273-4437-486b-a0e7-0f3c4740814f.png)
