### ISSUE TITLE
1.18 Timeout Error 

### ISSUE THREAD

**Issue by weihao** [GriefPrevention/GriefPrevention#1688] opened 2021-12-03 03:19 UTC
### Observed Behavior

This error occurred whenever a new user joins

### Expected Behavior

N/A

### Reproduction steps

Paper 1.18

### Stack trace or error log

```shell
[02:29:33 INFO]: [GriefPrevention] com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 42,768,157 milliseconds ago. The last packet sent successfully to the server was 42,768,163 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use 
in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
        at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.DatabaseDataStore.getPlayerDataFromStorage(DatabaseDataStore.java:497)
        at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.PlayerData.loadDataFromSecondaryStorage(PlayerData.java:212)
        at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.PlayerData.getClaims(PlayerData.java:271)
        at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.GriefPrevention.isNewToServer(GriefPrevention.java:3650)
        at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerJoin(PlayerEventHandler.java:687)
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359)
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301)
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:306)
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:526)
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1469)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1263)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 42,768,157 milliseconds ago. The last packet sent successfully to the server was 42,768,163 milliseconds ago. is longer than the server configured value of 'wait_timeout'. 
You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:567)
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:622)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:987)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
        ... 21 more
Caused by: java.net.SocketException: Broken pipe
        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
        at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:340)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1298)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:558)
        ... 25 more
```

### Server version

```shell
This server is running Paper version git-Paper-21 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: a5a7782)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
sql enabled

  Database:
    URL: jdbc:mysql://db:3306/example
    UserName: root
```
```


### Plugin list

```shell
floodgate, GriefPrevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-12-03 03:54
Duplicate of #1312

**Closed as completed by Jikoo** 2021-12-03 03:54 UTC
