### ISSUE TITLE
Villagers do not convert to Zombies inside claims

### ISSUE THREAD

**Issue by Spoonerj1** [GriefPrevention/GriefPrevention#1064] opened 2020-10-19 23:22 UTC
### What happened:
Villagers are not converted into zombies when killed in hard mode.

### What was expected:
Hard mode has a 100% conversion rate for villagers into zombies 

### Steps to reproduce:

1. spawn a villager and a zombie outside of a claim to verify that villagers convert to zombies. 
2. spawn a villager and zombie inside a claim, the villager will be killed.

### Server and GriefPrevention version:
Paste of `/version`:  Server: Paper(231) 1.16.3-R0.1-SNAPSHOT 
(I use the version provided by the host in the console, which to my knowledge is updated weekly)

Paste of `/version GriefPrevention`: GriefPrevention version 16.16.0 (same issue was present in 16.14.0)

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by Spoonerj1** [comment] 2020-10-19 23:34
Issue persists after unclaiming the area as well. I have also tried this after restarting. In a non-claimed (has not been claimed at all) area, villagers convert normally...

1. Claim area
2. spawn villager
3. spawn zombie
4. observe death of villager

5. abandon claim
6. repeat 2-4

7. restart server
8. repeat 2-4

**Comment by Jikoo** [comment] 2020-10-20 00:40
Cannot reproduce. Please include your config.

You have likely enabled the creative ruleset, which includes a limit on entities of area/50, completely blocking spawning outside of claims. Depending on when the new entity is spawned during the conversion process, it's possible that the entity count is currently 2 for a 10x10 claim (even though one is dying) so the new entity cannot be spawned.

If you don't want to use the creative features but do want players to have to claim area to build, try using SurvivalRequiringClaims instead.

**Comment by Spoonerj1** [comment] 2020-10-20 19:46
I've had the same config (minus world names) for about 5 years and this is the first time we have had any issue.

Casimir is the world name. 
[GPconfig.txt](https://github.com/TechFortress/GriefPrevention/files/5411183/GPconfig.txt)

**Comment by Spoonerj1** [comment] 2020-10-20 19:56
In the server where this is an issue it affects only one player, if I travel a short way away (+/- 50 blocks) from where they have built it, everything functions normally/as expected. But as soon as the area is claimed, the villagers stop converting

**Comment by Spoonerj1** [comment] 2020-10-20 20:17
I was just online again and the player having the issue says its working now, I verified a single zombie, but have not yet figured out what changed, I haven't made any adjustments since yesterday.

**Comment by Jikoo** [comment] 2020-10-20 20:32
So to confirm, you have actually personally successfully reproduced this on a fresh server running only GP using your current config? I ask because you checked those options in the form, but it really doesn't sound like that's the case based on your replies.

Any rate, I can't test using your config for another couple hours, but I can assure you that GP [only messes with spawning when the creative ruleset is enabled](https://github.com/TechFortress/GriefPrevention/blob/202f03e04c0efbb2daf0845e12d3935455b09ea2/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L461). It's certainly possible that something's hooking GP (particularly if it continues to happen after the claim is removed), we've seen it before.

**Comment by Spoonerj1** [comment] 2020-10-20 20:37
Correct, I tested this on a server running the same version of paper and GP. I did not try it on spigot.  I will begin looking closer for a hook that may be the issue, but I don't think that would be the case since I was able to reproduce with only GP installed. 

I have not used the creative rule set on my server (even in a creative world) because its a bit easier for players to use something like plots squared in those worlds.

**Comment by Jikoo** [comment] 2020-10-21 00:55
I'm unable to reproduce. Replaced "casimir" with "world" in your provided config and tried various layouts. Conversion was always successful. Tried in and out of claims and in and out of vanilla spawn protection using Paper 244, GP 16.16.0.

**Comment by Jikoo** [comment] 2020-10-21 01:03
Found a "case" - if the zombie is burning and the villager dies to fire tick and not an actual hit, conversion does not occur. That's not a GP thing though, the final hit has to be direct damage from a zombie.

**Comment by Spoonerj1** [comment] 2020-10-25 23:15
I will attempt to get more info. perhaps GP is not playing nice with something else on the server and I just haven't found it yet.

**Comment by Jikoo** [comment] 2020-12-10 16:38
Going to close this as it appears to be a plugin misbehaving (similar to #922) and not a fault in GP. If you do end up doing more research and finding the cause, please keep us posted.

**Closed as completed by Jikoo** 2020-12-10 16:38 UTC
Labels: Need more info, 🚫Cannot Reproduce
