### ISSUE TITLE
[Request] Option to change more message.

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#143] opened 2017-06-06 11:41 UTC
This is a great plugin. Simple to use. And not hard to understand. But there is a lack of Editable message what is a huge disappointment. So can you please add much more to the message.yml?

**Comment by RoboMWM** [comment] 2017-06-06 19:42
What things in the messages.yml would you like to see that aren't already there?

**Comment by RoboMWM** [comment] 2018-09-06 18:41
Closed in favor of duplicate but more specific request #191

**Comment by RoboMWM** [comment] 2018-09-06 18:42
Duplicate of #191

**Closed as completed by RoboMWM** 2018-09-06 18:41 UTC
