### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by colue** [GriefPrevention/GriefPrevention#2222] opened 2024-02-18 21:39 UTC
### Observed Behavior

the plugin keeps giving errors over and over

### Expected Behavior

no error

### Reproduction steps

happens all the time no matter what players do

### Stack trace or error log

```shell
gist:d7b9e01c0c877d40cfe22e8e1777629f 

https://gist.github.com/colue/d7b9e01c0c877d40cfe22e8e1777629f
```

### Server version

```shell
This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)
You are running the latest version
Previous version: git-Paper-"e9e0bc1" (MC: 1.20.4)
```

### GriefPrevention version

```shell
18.02 21:38:54 [Server] [INFO] GriefPrevention version 16.18.1
```

### Configuration

```yaml
havent changed anything yet starndered install
```

### Plugin list

```shell
18.02 21:38:07 [Server] [INFO] Server Plugins (30):
18.02 21:38:07 [Server] [INFO] Bukkit Plugins:
18.02 21:38:07 [Server] [INFO] - AdvancedEnchantments, BannerMaker, BlueMap, BlueMapDeathMarkers, BlueMapSkinIntegration, BottledExp, CMI, *CMIEInjector, CMILib, CombatPlus
18.02 21:38:07 [Server] [INFO] CoreProtect, EpicHeads, EpicHoppers, EpicRename, EpicSpawners, GriefPrevention, LuckPerms, PlaceholderAPI, ProtocolLib, ResourceWorld
18.02 21:38:07 [Server] [INFO] ShopGUIPlus, spark, UltimateFishing, UltimateModeration, UltimateStacker, UltimateTimber, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2024-02-18 22:36
Duplicate of #2214

**Closed as not planned by Jikoo** 2024-02-18 22:36 UTC
