### ISSUE TITLE
[Suggestion] Building/breaking blocks vertically

### ISSUE THREAD

**Issue by Lammendam** [GriefPrevention/GriefPrevention#582] opened 2019-08-09 16:49 UTC
**AS** an administrator
**I WANT** to define vertical size (y-coord) of subdivided claims and to prevent players to place/break blocks in this area in addition to x and z size.
**BECAUSE** existing plugin functionaluty lacks this feature and it important to use for claims that need to make breakable without ruining land in subdivided claim.

For example, i have a custom automatic mine that contains a few lodes that automatically resets after 10 minutes. Of course, it in the spawn claim. And for these lodes I created a few subdivided claims that allow build inside, but not on parent (spawn) claim. Currently, players can build down to bedrock.

Another example. I have a city (e.g. admin claim) and players cant build inside. I have made a few quests that requires to build/break blocks on the city land. For this i create a subdivided claim and allow players to build there. Unfortunatelly, they can get down to bedrock, make a hole, where other players may die due to fall from big height...

**Comment by RoboMWM** [comment] 2019-08-09 16:57
Can you please fill out the Gherkin statement, as I do not understand what this request is

**Comment by Lammendam** [comment] 2019-08-09 17:42
I know that this violates the principle of ease of use of the plugin, but i think the height of the claim also matters...

**Comment by RoboMWM** [comment] 2019-08-09 17:45
Thanks for updating the OP. I just saw a lot of text regarding why build/break shouldn't happen on "inside" but had no definition of what "inside" is.

**Comment by RoboMWM** [comment] 2019-08-09 17:45
Duplicate of #269

**Closed as completed by RoboMWM** 2019-08-09 17:45 UTC
