### ISSUE TITLE
Claim not dissapwaring after 30 days

### ISSUE THREAD

**Issue by Joeythemlgprogamer11** [GriefPrevention/GriefPrevention#1109] opened 2020-11-22 22:18 UTC
Hey there, on our server claims where players didnt log on for 30 days would dissapear but now they dont 

I dont think we changed anything but to be sure how would we revert it back to the original, thanks

**Comment by Joeythemlgprogamer11** [comment] 2020-11-22 22:19
@bigpresh @Jikoo @RoboMWM sorry idrk how git hub works lol

**Comment by Joeythemlgprogamer11** [comment] 2020-11-22 22:22
Sorry i made like 20 of these... Idk how to delete them :( sorry

**Comment by Jikoo** [comment] 2020-11-22 23:01
Think of GH like a forum with extra features for developers, issues are like topics. In the future if you do open accidental issues, please don't @ mention people when you do, just close them - the mention guarantees the person will get another notification, where just closing the issue will make it clear that no interaction is needed.

Re: your issue - Please try [GPClaimExpiration](https://github.com/GPAddons/GPClaimExpiration). A build of GPCE is available [here](https://ci.appveyor.com/project/Jikoo/gpclaimexpiration/build/artifacts). If you continue to have issues with claims expiring with GPCE enabled (note that it uses its own settings, not GP's!), please open an issue on GPCE's tracker.

Note that GPCE doesn't support auto-restorenature at this time, that'll probably be a separate addon.

**Comment by Jikoo** [comment] 2020-11-22 23:01
Duplicate of #496

**Closed as completed by Jikoo** 2020-11-22 23:01 UTC

**Comment by RoboMWM** [comment] 2020-11-26 04:27
Tbh, the linked issue has details (offline mode is true for example) and extraneous conversation that I've personally unsubscribed from it, I'd rather have a new issue with proper details and testing. For me on my server, I just recently modified the accrued limit and a ton of claims started expiring so ya.
