### ISSUE TITLE
Command /gpblockinfo (in 1.13)

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#327] opened 2018-07-27 05:59 UTC
### What behaviour is observed:
I came across the command /gpblockinfo (because of the tabcompleter) and it ran an error in the console. I dont see this command in the command list, Im guessing its not actually used, but figured I'd bring it to your attention
### What behaviour is expected:
¯\_(ツ)_/¯
### Steps/models to reproduce:
type /gpblockinfo
### Spigot/Craftbukkit/Paper and GriefPrevention version:
[22:57:46 INFO]: This server is running CraftBukkit version git-Spigot-0b44fa0-1ef1ffd (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[22:58:06 INFO]: GriefPrevention version 16.8

### Stack trace/error

```
[22:57:28 INFO]: ShaneBee issued server command: /gpblockinfo
[22:57:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gpblockinfo' in plugin GriefPrevention v16.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.IllegalFormatConversionException: d != org.bukkit.Material
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_181]
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_181]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_181]
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_181]
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_181]
	at java.lang.String.format(String.java:2940) ~[?:1.8.0_181]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:2649) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-0b44fa0-1ef1ffd]
	... 15 more
```

### GriefPrevention config.yml (if applicable)

I dont think it's needed? But Its just the default one, I haven't touched it.
### Plugin list (if applicable):
-GriefPrevention
That's it, I ran it with no plugins

**Comment by RoboMWM** [comment] 2018-07-27 06:04
Duplicate of #313

**Closed as completed by RoboMWM** 2018-07-27 06:04 UTC
