### ISSUE TITLE
Error on 1.13 (/claim)

### ISSUE THREAD

**Issue by cloakfox** [GriefPrevention/GriefPrevention#335] opened 2018-08-01 21:59 UTC
### What behaviour is observed:
https://hastebin.com/hexeweromu.md
### What behaviour is expected:
https://hastebin.com/hexeweromu.md
### Steps/models to reproduce:
https://hastebin.com/hexeweromu.md (using /claim command)
### Spigot/Craftbukkit/Paper and GriefPrevention version:
spigot 1.13 builds (latest, 01-08)

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by RoboMWM** [comment] 2018-08-03 20:31
Duplicate of #319

**Closed as completed by RoboMWM** 2018-08-03 20:31 UTC
