### ISSUE TITLE
Item Frame && Painting not protected by claim

### ISSUE THREAD

**Issue by tommasobenatti** [GriefPrevention/GriefPrevention#2171] opened 2023-11-14 19:55 UTC
### Observed Behavior

Untrusted players can break placed Item Frames and Paintings, even if the're protected under a GriefPrevention claim

### Expected Behavior

Untrusted players shouldn't have the ability to break placed Item Frames and Painting

### Reproduction steps

1. Create a claim, inside of it place item frames && paintings
2. Log with an untrusted account and try to break them
3. See

### Server version

```shell
[20:53:08 INFO]: This server is running Pufferfish version git-Pufferfish-27 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)
```

### GriefPrevention version

```shell
[20:53:33 INFO]: GriefPrevention version e49446d
(latest commit available)
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    eventi_temp: -1
    vecchiospawn: -1
  Claims:
    Mode:
      vecchiospawn: Disabled
      world_the_end: Disabled
      world: Survival
      world_nether: Survival
      eventi_temp: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 20000
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 0
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: '[]'
    WhisperSlashCommands: '[]'
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      eventi_temp: true
      vecchiospawn: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - CYAN_WOOL
    - FERN
    - COBBLESTONE
    - WHITE_WOOL
    - PINK_WOOL
    - SNOW
    - GRAVEL
    - GLASS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - OAK_PLANKS
    - ORANGE_WOOL
    - GLASS_PANE
    - SPRUCE_PLANKS
    - YELLOW_WOOL
    - RED_WOOL
    - DIRT
    - MAGENTA_WOOL
    - BROWN_WOOL
    - GRASS_BLOCK
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - DEAD_BUSH
    - PURPLE_WOOL
    - BLACK_WOOL
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - LIME_WOOL
    - BLUE_WOOL
    - GREEN_WOOL
    - LIGHT_BLUE_WOOL
    - GRASS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2023-11-14 20:35
Duplicate of #2145

**Closed as completed by Jikoo** 2023-11-14 20:35 UTC
Labels: 🚫Not a GP issue

**Comment by Jikoo** [comment] 2023-11-14 20:39
Like Robo said on the linked issue, it's almost certainly a plugin conflict, which is further reinforced by the fact that you could not reproduce with only GP installed. You also didn't provide your plugin list, so we can't really help you.
You can either use EventDebug or a similar plugin to identify which plugins it could be by checking who listens to the HangingBreakEvent or you can add your plugins half at a time to more swiftly narrow down the culprit.
