### ISSUE TITLE
Cannot place a book in a lectern with containertrust

### ISSUE THREAD

**Issue by lemafor** [GriefPrevention/GriefPrevention#613] opened 2019-09-06 16:22 UTC
### What happened:
Claim with "container trust". I can read a book on the lectern, I can take a book from the lectern. But I can't place a book to the lectern - is it OK?
 
### What you expected:
With container trust I can both take a book from the lectern and place a book to the lectern.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
[18:20:56] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-065a373-763e560 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[18:20:56] [Server thread/INFO]: You are running the latest version

Paste of `/version GriefPrevention`:
16.12.0-d4d7ac4

**Comment by RoboMWM** [comment] 2019-09-06 16:46
@ShaneBeee @zedwick

**Comment by ShaneBeee** [comment] 2019-09-06 16:52
I can not replicate this issue.
I went into a claim that is not mine, results:
no perms:
can't read book, cant remove/place a book

access trust:
I can read book, 
I cant remove/place book

container trust:
I can read book, remove book, place book

**Comment by lemafor** [comment] 2019-09-06 18:46
I tried "book and quill" and "written book" - I can't place it. 
Here is my video: https://www.youtube.com/watch?v=G-G9v26-F9U
And screenshot with trustlist.

**Comment by ShaneBeee** [comment] 2019-09-06 18:48
I’ll watch the video when I get home but as an owner of a claim can you place one? Just want to rule out other plugins preventing this

**Comment by lemafor** [comment] 2019-09-06 19:01
I am not an owner, this is claim of Zoabel. Here is /trustlist
![clpB0A9](https://user-images.githubusercontent.com/44153509/64453675-68758380-d0e9-11e9-95ac-c29f5dbb423f.png)

**Comment by ShaneBeee** [comment] 2019-09-06 19:13
Yes I’m aware.  I’m asking if I’m a claim you do own, are you able to place a nook on a lectern?

**Comment by lemafor** [comment] 2019-09-06 19:18
Yes. On my own claim I can place a book on a lectern. Just tried it.

**Comment by ShaneBeee** [comment] 2019-09-06 20:01
Can you please try re-downloading the latest GP.

I have tried to replicate this under every condition.
Im added to this persons claim with container trust, I'm NOT OP, and I'm able to place the book as intended.

[**VIDEO**](https://www.youtube.com/watch?v=h5KexvlU5W0)

**Comment by zedwick** [comment] 2019-09-07 12:18
Cannot reproduce with 16.12.0-d4d7ac4. (Though I only tested with Paper-157)

@lemafor Please provide the output of /plugins, and if possible try to reproduce the issue with no other plugins installed.

**Comment by ShaneBeee** [comment] 2019-09-08 17:59
Ok did more testing. This is really odd, but for some reason it works on Paper, but does not work on Spigot. 

Ill be working on a fix for this ASAP.

**Closed as completed** 2019-09-08 18:50 UTC
Labels: 🐛Bug, 🚫Not a GP issue

**Comment by lemafor** [comment] 2019-09-09 05:50
All plugins disabled except of GP but problem is the same. Still: "You don't have X's permission to build here". 
Why "permission to build" when I only want to put a book to a lectern?

**Comment by ShaneBeee** [comment] 2019-09-09 05:56
Did you build a new GP jar? Because Robo never actually pushed a new release.

**Comment by lemafor** [comment] 2019-09-09 05:57
I have this:
[07:57:20] [Server thread/INFO]: GriefPrevention version 16.12.0-d4d7ac4

**Comment by ShaneBeee** [comment] 2019-09-09 05:59
yeah, I literally just said, Robo never pushed a release, so you will have to manually build a new jar file from this repo if you so wish to have that fix right away.

**Comment by lemafor** [comment] 2019-09-09 06:02
I am sorry, I'm not so advanced to build a new jar file myself. I have never done that. I don't know how to do it  :(.

**Comment by RoboMWM** [comment] 2019-09-10 00:46
https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/27265294/artifacts

**Comment by lemafor** [comment] 2019-09-10 03:42
Thanks a lot, now it works!
