### ISSUE TITLE
Not working on 1.13 spigot caused by world guard

### ISSUE THREAD

**Issue by ozm8** [GriefPrevention/GriefPrevention#332] opened 2018-08-01 10:49 UTC
What happens:
When claiming an area nothing happens, no messages or anything.
I think the issue is to do with world guard
Error:
https://pastebin.com/yfbCSmLP

**Comment by bigpresh** [comment] 2018-08-01 11:00
Yeah, looks like a WorldGuard issue.

You'll probably want to wait until GriefPrevention and WorldGuard have 1.13-ready-and-tested releases out.

In the meantime, you could try disabling WorldGuard integration with the `GriefPrevention.Claims.CreationRequiresWorldGuardBuildPermission` config setting (FIXME: I note that this isn't well documented - the wiki mentions only:

> Note that by default, GriefPrevention will not allow a player to create a land claim which overlaps a WorldGuard region he doesn't have permission to build in. You can disable this feature in the config file.

... but doesn't tell you how to disable that.  I'll raise a new issue for that.

**Comment by bigpresh** [comment] 2018-08-01 11:04
Raised #333 as a TODO for improving the config doco on the wiki.

**Comment by mirolm** [comment] 2018-08-03 07:52
There are WG/WE 1.13 experimental builds. I will try to fix the WG wrapper code and post a PR.

**Comment by RoboMWM** [comment] 2018-08-05 13:27
Duplicate of #329

**Closed as completed by RoboMWM** 2018-08-05 13:27 UTC
