### ISSUE TITLE
Claim ID Issue

### ISSUE THREAD

**Issue by Dreamthief01** [GriefPrevention/GriefPrevention#139] opened 2017-06-03 15:53 UTC
There seems to be a maximum claim ID of 9999 and after that the claim id tracker file appears to reset to zero and start over.  This is causing my oldest claims to have their associated claim ID file overwritten by a new player creating a new claim which then takes that same ID number.  

My server is about 2 years old and all of my player's oldest spawns are now becoming unclaimed by new players creating new claims.  

Can we remove this cap or change it over to an integer or something else large enough to never be capped.  Please let me know if i missed a config file setting somewhere that governs this.  

No real stack trace or error per say on this issue.

Thanks,

Dreamthief01,
TerminalServer.us

**Comment by zedwick** [comment] 2017-06-03 16:45
Are you sure it's 9999? I have claims with IDs beyond 16000

**Comment by Jikoo** [comment] 2017-06-03 17:15
Could be a duplicate of #120 - my current nextClaimID is 20562993, it's certainly not capped to 9999. Consider shutting down the server and manually fixing `GriefPreventionData/ClaimData/_nextClaimID`.

**Comment by Dreamthief01** [comment] 2017-06-03 17:53
Ah, my mistake, I see now that I do have ids in the 11,000s but the way my list was sorted 9999 was the highest i was seeing.  Looks like something reset my file.  Ill manually adjust it.  Thanks!

**Comment by Dreamthief01** [comment] 2017-06-03 18:32
Although I was wrong about this issue, this still seems like an odd way to code this.  Doesn't the system need to read in all of the files on load anyhow and cant it just figure out what the next number should be based on the highest one it read in?  Then just use and increment that tracker in memory until next server startup.  What was the benefit of storing that tracker counter in a separate file I wonder.

**Comment by RoboMWM** [comment] 2017-06-03 20:14
> Doesn't the system need to read in all of the files on load anyhow and cant it just figure out what the next number should be based on the highest one it read in? Then just use and increment that tracker in memory until next server startup. What was the benefit of storing that tracker counter in a separate file I wonder.

Perhaps some people move/freeze/other backup claim files, and then want to move them back in? Also, if anything uses the API for claim IDs, it'd be better that each unique claim has a unique ID. That being said, will likely implement this idea to "recover" a broken `_nextClaimID` file

> Looks like something reset my file. Ill manually adjust it.

Likely due to a full hard drive, or other I/O corruption.

**Comment by RoboMWM** [comment] 2018-09-04 18:39
Also referenced in #207, closed with commit https://github.com/TechFortress/GriefPrevention/commit/e17403feb2e8bef41099421e46e00ee2acf9c04e

**Closed as completed by RoboMWM** 2018-09-04 18:39 UTC
