### ISSUE TITLE
Bedrock players connected via Geyser/Floodgat. Trusted to a Java version made claim are unable to perform actions.

### ISSUE THREAD

**Issue by MCTGE** [GriefPrevention/GriefPrevention#1653] opened 2021-11-10 06:53 UTC
### Observed Behavior

Players that connect to my survival server through Geyser are able to create claims and interact with their own.  However, when a Java player tries to trust a Bedrock player to their claim .  The chat message shows that the command worked yet those players are not able to access their proper trust permissions. 

### Expected Behavior

Bedrock players should be able to access areas they have permissions in. 

### Reproduction steps

Example:
Steve is on java and /trust his mobile version account, Alex.  It will tell Steve that Alex is now trusted however, Alex can not open any chest/break blocks.

### Stack trace or error log

```shell
[09.11 18:43:49] [Server] [INFO] Golden_Goat_ issued server command: /trust .Ka_Guardian

There is no further information to display this is all GP is providing.
```

### Server version

```shell
This server is running Paper version git-Paper-375 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 87121ce)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-373 (MC: 1.17.1)
```

### GriefPrevention version

```shell
16.17.1-2b69191
```

### Configuration

```yaml
https://pastebin.com/QuhZniAu
```

### Plugin list

```shell
[09.11 18:52:58] [Server] [INFO] Plugins (60): AdvancedAchievements, AdvancedCrates, ArmorStandTools, AuctionHouse, BetterPing*, BungeeGuard, BuycraftX, ChatItemDisplay, ChestShop, Citizens, CitizensGUI, CMILib, ColoredAnvils, CommandPanels, CoreProtect, DailyRewardsPlus, DeadChest, DeathMessages, DiscordSRV, dtlTraders, dynmap, EpicRename, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GriefPrevention, GSit, Guilds, HeadDatabase, HolographicDisplays, HomeGUI, Images, InvSeePlusPlus, Jobs, LibsDisguises, LuckPerms, mcMMO, MobArena, MyCommand, PetMaster, PlaceholderAPI, Plan, PlayerHeads, PlayerWarps, ProtocolLib, PvPManager, Quests, RealScoreboard, sleep-most, spark, SurvivalInvisiframes, TAB, TouchscreenHolograms, TradeMe, UltraCosmetics, Vault, VentureChat, Votifier, VotingPlugin, WorldGuard
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [x] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment] 2021-11-10 10:41
Duplicate of #1360

**Closed as completed by Jikoo** 2021-11-10 10:41 UTC
